// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package aws

const (
	AWSProviderSource          = "https://github.com/hashicorp/terraform-provider-aws"
	AWSProviderVersion         = "v6.63.0"
	AWSProviderCommit          = "07c0e849a5d45731848cc9b10eab557cbc141d76"
	AWSProviderLicense         = "MPL-2.0"
	AWSProviderDefinitionCount = 2640
)
