// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var AmpDefinitions = [...]string{
	"aws_prometheus_anomaly_detector",
	"aws_prometheus_scraper",
	"aws_prometheus_scraper_logging_configuration",
}
