// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var ApigatewayDefinitions = [...]string{
	"aws_api_gateway_integration",
	"aws_api_gateway_integration_response",
	"aws_api_gateway_method",
	"aws_api_gateway_method_response",
	"aws_api_gateway_resource",
	"aws_api_gateway_rest_api",
}
