// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var AppautoscalingDefinitions = [...]string{
	"aws_appautoscaling_policy",
	"aws_appautoscaling_target",
}
