// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var BackupDefinitions = [...]string{
	"aws_backup_plan",
	"aws_backup_selection",
	"aws_backup_vault",
}
