// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var BedrockagentcoreDefinitions = [...]string{
	"aws_bedrockagentcore_browser_profile",
	"aws_bedrockagentcore_evaluator",
	"aws_bedrockagentcore_gateway_rule",
	"aws_bedrockagentcore_harness",
	"aws_bedrockagentcore_online_evaluation_config",
	"aws_bedrockagentcore_policy",
	"aws_bedrockagentcore_policy_engine",
	"aws_bedrockagentcore_registry",
	"aws_bedrockagentcore_resource_policy",
}
