// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var CloudfrontDefinitions = [...]string{
	"aws_cloudfront_distribution",
	"aws_cloudfront_key_value_store",
}
