// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var CloudwatchDefinitions = [...]string{
	"aws_cloudwatch_alarm_mute_rule",
	"aws_cloudwatch_metric_alarm",
}
