// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var ConfigserviceDefinitions = [...]string{
	"aws_config_config_rule",
	"aws_config_remediation_configuration",
}
