// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var DynamodbDefinitions = [...]string{
	"aws_dynamodb_global_secondary_index",
	"aws_dynamodb_table",
	"aws_dynamodb_table_item",
}
