// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var Ec2Definitions = [...]string{
	"aws_ami_launch_permission",
	"aws_ebs_volume",
	"aws_ec2_network_insights_access_scope",
	"aws_ec2_secondary_network",
	"aws_ec2_secondary_subnet",
	"aws_ec2_transit_gateway_metering_policy",
	"aws_eip",
	"aws_flow_log",
	"aws_instance",
	"aws_internet_gateway",
	"aws_key_pair",
	"aws_launch_template",
	"aws_nat_gateway",
	"aws_network_interface",
	"aws_route",
	"aws_route_table",
	"aws_route_table_association",
	"aws_security_group",
	"aws_subnet",
	"aws_volume_attachment",
	"aws_vpc",
	"aws_vpc_endpoint",
	"aws_vpc_endpoint_route_table_association",
	"aws_vpc_security_group_egress_rule",
	"aws_vpc_security_group_ingress_rule",
}
