// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var EcrDefinitions = [...]string{
	"aws_ecr_lifecycle_policy",
	"aws_ecr_repository",
	"aws_ecr_repository_policy",
}
