// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var EcsDefinitions = [...]string{
	"aws_ecs_cluster",
	"aws_ecs_daemon",
	"aws_ecs_daemon_task_definition",
	"aws_ecs_service",
	"aws_ecs_task_definition",
}
