// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var EksDefinitions = [...]string{
	"aws_eks_access_entry",
	"aws_eks_access_policy_association",
	"aws_eks_addon",
	"aws_eks_cluster",
	"aws_eks_node_group",
}
