// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var Elbv2Definitions = [...]string{
	"aws_lb",
	"aws_lb_listener",
	"aws_lb_listener_rule",
	"aws_lb_target_group",
	"aws_lb_target_group_attachment",
}
