// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var IamDefinitions = [...]string{
	"aws_iam_access_key",
	"aws_iam_group_policy_attachment",
	"aws_iam_instance_profile",
	"aws_iam_policy",
	"aws_iam_role",
	"aws_iam_role_policy",
	"aws_iam_role_policy_attachment",
	"aws_iam_user",
	"aws_iam_user_policy_attachment",
}
