// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var KafkaDefinitions = [...]string{
	"aws_msk_cluster",
	"aws_msk_serverless_cluster",
	"aws_msk_topic",
}
