// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var LambdamicrovmsDefinitions = [...]string{
	"aws_lambdamicrovms_image",
	"aws_lambdamicrovms_microvm",
}
