// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var LambdaDefinitions = [...]string{
	"aws_lambda_capacity_provider",
	"aws_lambda_event_source_mapping",
	"aws_lambda_function",
	"aws_lambda_function_scaling_config",
	"aws_lambda_layer_version",
	"aws_lambda_permission",
}
