// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var LogsDefinitions = [...]string{
	"aws_cloudwatch_log_group",
	"aws_cloudwatch_log_metric_filter",
	"aws_cloudwatch_log_s3_table_integration_source",
	"aws_cloudwatch_log_stream",
	"aws_cloudwatch_log_subscription_filter",
}
