// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var ObservabilityadminDefinitions = [...]string{
	"aws_observabilityadmin_telemetry_rule",
	"aws_observabilityadmin_telemetry_rule_for_organization",
}
