// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var Pinpointsmsvoicev2Definitions = [...]string{
	"aws_pinpointsmsvoicev2_event_destination",
	"aws_pinpointsmsvoicev2_keyword",
	"aws_pinpointsmsvoicev2_pool",
	"aws_pinpointsmsvoicev2_resource_policy",
	"aws_pinpointsmsvoicev2_sender_id",
}
