// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var RdsDefinitions = [...]string{
	"aws_db_instance",
	"aws_db_parameter_group",
	"aws_db_subnet_group",
	"aws_rds_cluster",
}
