// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var Route53Definitions = [...]string{
	"aws_route53_record",
	"aws_route53_vpc_association_authorization",
	"aws_route53_zone",
	"aws_route53_zone_association",
}
