// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var Route53resolverDefinitions = [...]string{
	"aws_route53_resolver_rule",
	"aws_route53_resolver_rule_association",
}
