// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var S3Definitions = [...]string{
	"aws_s3_bucket",
	"aws_s3_bucket_acl",
	"aws_s3_bucket_lifecycle_configuration",
	"aws_s3_bucket_logging",
	"aws_s3_bucket_notification",
	"aws_s3_bucket_ownership_controls",
	"aws_s3_bucket_policy",
	"aws_s3_bucket_public_access_block",
	"aws_s3_bucket_server_side_encryption_configuration",
	"aws_s3_bucket_versioning",
	"aws_s3_directory_bucket",
	"aws_s3_object",
}
