// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var S3controlDefinitions = [...]string{
	"aws_s3control_multi_region_access_point",
	"aws_s3control_multi_region_access_point_routes",
}
