// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var S3filesDefinitions = [...]string{
	"aws_s3files_access_point",
	"aws_s3files_file_system",
	"aws_s3files_file_system_policy",
	"aws_s3files_mount_target",
	"aws_s3files_synchronization_configuration",
}
