// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var SagemakerDefinitions = [...]string{
	"aws_sagemaker_algorithm",
	"aws_sagemaker_hub_content_reference",
	"aws_sagemaker_hyper_parameter_tuning_job",
	"aws_sagemaker_training_job",
}
