// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var SecretsmanagerDefinitions = [...]string{
	"aws_secretsmanager_secret",
	"aws_secretsmanager_secret_policy",
	"aws_secretsmanager_secret_version",
}
