// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var SecurityhubDefinitions = [...]string{
	"aws_securityhub_automation_rule_v2",
	"aws_securityhub_connector_v2",
	"aws_securityhub_insight",
	"aws_securityhub_standards_control",
}
