// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var SnsDefinitions = [...]string{
	"aws_sns_topic",
	"aws_sns_topic_policy",
	"aws_sns_topic_subscription",
}
