// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var SsmDefinitions = [...]string{
	"aws_ssm_association",
	"aws_ssm_document",
	"aws_ssm_parameter",
	"aws_ssm_patch_baseline",
	"aws_ssm_patch_group",
}
