// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package listresource

var WorkmailDefinitions = [...]string{
	"aws_workmail_domain",
	"aws_workmail_group",
	"aws_workmail_organization",
	"aws_workmail_user",
}
