// Command awsdefinitions synchronizes the Terraform AWS Provider definition
// inventory used by the xaligo AWS mapping profile.
package main

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	providerSource        = "https://github.com/hashicorp/terraform-provider-aws"
	providerLicense       = "MPL-2.0"
	releasesAPI           = "https://api.github.com/repos/hashicorp/terraform-provider-aws/releases"
	commitsAPI            = "https://api.github.com/repos/hashicorp/terraform-provider-aws/commits"
	generatedRootRelative = "internal/entity/aws"
	metadataRelative      = "internal/entity/aws/provider_metadata_gen.go"
	groupsRelative        = "internal/entity/aws/provider_definition_groups_gen.go"
	legacyRelative        = "internal/entity/aws/provider_definitions_gen.go"
	snapshotRelative      = "test/internal/entity/aws/testdata/terraform-provider-aws.json"
	maximumSourceFileLen  = 16 << 20
	generatedHeader       = "// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.\n"
)

var (
	fullCommitPattern = regexp.MustCompile(`^[0-9a-f]{40}$`)
	servicePattern    = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
	definitionKinds   = []string{"action", "data_source", "ephemeral_resource", "function", "list_resource", "resource"}
)

type definition struct {
	Kind     string `json:"kind"`
	Service  string `json:"service"`
	TypeName string `json:"type_name"`
}

type snapshot struct {
	Source      string       `json:"source"`
	Version     string       `json:"version"`
	Commit      string       `json:"commit"`
	License     string       `json:"license"`
	Definitions []definition `json:"definitions"`
}

type definitionGroup struct {
	Kind      string
	Service   string
	TypeNames []string
}

type releaseMetadata struct {
	TagName         string `json:"tag_name"`
	TargetCommitish string `json:"target_commitish"`
	TarballURL      string `json:"tarball_url"`
}

type githubClient struct {
	http  *http.Client
	token string
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "awsdefinitions:", err)
		os.Exit(1)
	}
}

func run(arguments []string) error {
	if len(arguments) == 0 {
		return errors.New("usage: go run ./tools/awsdefinitions <update|generate|check-latest> [flags]")
	}
	switch arguments[0] {
	case "update":
		return runUpdate(arguments[1:])
	case "generate":
		return runGenerate(arguments[1:])
	case "check-latest":
		return runCheckLatest(arguments[1:])
	default:
		return fmt.Errorf("unknown command %q", arguments[0])
	}
}

func runUpdate(arguments []string) error {
	flags := flag.NewFlagSet("update", flag.ContinueOnError)
	repositoryRoot := flags.String("repo", ".", "repository root")
	version := flags.String("version", "latest", "release tag or latest")
	if err := flags.Parse(arguments); err != nil {
		return err
	}

	client := newGitHubClient()
	release, err := client.release(*version)
	if err != nil {
		return err
	}
	commit, err := client.commit(release)
	if err != nil {
		return err
	}
	definitions, err := client.definitions(release.TarballURL)
	if err != nil {
		return err
	}
	inventory := snapshot{
		Source:      providerSource,
		Version:     release.TagName,
		Commit:      commit,
		License:     providerLicense,
		Definitions: definitions,
	}
	if err := validateSnapshot(inventory); err != nil {
		return err
	}
	if err := writeInventory(*repositoryRoot, inventory); err != nil {
		return err
	}
	fmt.Printf("updated AWS Provider definitions to %s (%s): %d definitions\n", inventory.Version, inventory.Commit, len(inventory.Definitions))
	fmt.Println("review the generated diff, then update the pinned integrity assertions in test/internal/entity/aws/definition_test.go")
	return nil
}

func runGenerate(arguments []string) error {
	flags := flag.NewFlagSet("generate", flag.ContinueOnError)
	repositoryRoot := flags.String("repo", ".", "repository root")
	snapshotPath := flags.String("snapshot", "", "snapshot path (defaults to the repository snapshot)")
	check := flags.Bool("check", false, "fail instead of writing when generated code differs")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	path := *snapshotPath
	if path == "" {
		path = filepath.Join(*repositoryRoot, snapshotRelative)
	}
	inventory, err := readSnapshot(path)
	if err != nil {
		return err
	}
	if err := validateSnapshot(inventory); err != nil {
		return err
	}
	generated, err := renderGeneratedFiles(inventory)
	if err != nil {
		return err
	}
	if *check {
		if err := checkGeneratedFiles(*repositoryRoot, generated); err != nil {
			return err
		}
		fmt.Printf("AWS Provider generated definitions are current: %s (%d definitions in %d kind/service files)\n", inventory.Version, len(inventory.Definitions), len(generated)-2)
		return nil
	}
	if err := writeGeneratedFiles(*repositoryRoot, generated); err != nil {
		return err
	}
	fmt.Printf("generated %d kind/service files below %s from %s (%d definitions)\n", len(generated)-2, generatedRootRelative, path, len(inventory.Definitions))
	return nil
}

func runCheckLatest(arguments []string) error {
	flags := flag.NewFlagSet("check-latest", flag.ContinueOnError)
	repositoryRoot := flags.String("repo", ".", "repository root")
	if err := flags.Parse(arguments); err != nil {
		return err
	}
	inventory, err := readSnapshot(filepath.Join(*repositoryRoot, snapshotRelative))
	if err != nil {
		return err
	}
	client := newGitHubClient()
	release, err := client.release("latest")
	if err != nil {
		return err
	}
	commit, err := client.commit(release)
	if err != nil {
		return err
	}
	if inventory.Version != release.TagName || inventory.Commit != commit {
		return fmt.Errorf("AWS Provider definitions are pinned to %s (%s), latest is %s (%s); run `make aws-definitions-update`", inventory.Version, inventory.Commit, release.TagName, commit)
	}
	fmt.Printf("AWS Provider definitions match latest release %s (%s)\n", release.TagName, commit)
	return nil
}

func newGitHubClient() *githubClient {
	return &githubClient{
		http:  &http.Client{Timeout: 5 * time.Minute},
		token: strings.TrimSpace(os.Getenv("GITHUB_TOKEN")),
	}
}

func (rcvr *githubClient) release(version string) (releaseMetadata, error) {
	endpoint := releasesAPI + "/latest"
	if version != "" && version != "latest" {
		endpoint = releasesAPI + "/tags/" + url.PathEscape(version)
	}
	var release releaseMetadata
	if err := rcvr.getJSON(endpoint, &release); err != nil {
		return releaseMetadata{}, fmt.Errorf("read AWS Provider release metadata: %w", err)
	}
	if release.TagName == "" || release.TarballURL == "" {
		return releaseMetadata{}, errors.New("AWS Provider release metadata is incomplete")
	}
	return release, nil
}

func (rcvr *githubClient) commit(release releaseMetadata) (string, error) {
	commit := strings.ToLower(strings.TrimSpace(release.TargetCommitish))
	if fullCommitPattern.MatchString(commit) {
		return commit, nil
	}
	var response struct {
		SHA string `json:"sha"`
	}
	if err := rcvr.getJSON(commitsAPI+"/"+url.PathEscape(release.TagName), &response); err != nil {
		return "", fmt.Errorf("resolve AWS Provider release commit: %w", err)
	}
	commit = strings.ToLower(strings.TrimSpace(response.SHA))
	if !fullCommitPattern.MatchString(commit) {
		return "", fmt.Errorf("resolved invalid AWS Provider commit %q", response.SHA)
	}
	return commit, nil
}

func (rcvr *githubClient) getJSON(endpoint string, target any) error {
	response, err := rcvr.get(endpoint)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if err := json.NewDecoder(response.Body).Decode(target); err != nil {
		return fmt.Errorf("decode %s: %w", endpoint, err)
	}
	return nil
}

func (rcvr *githubClient) get(endpoint string) (*http.Response, error) {
	request, err := http.NewRequest(http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, err
	}
	request.Header.Set("Accept", "application/vnd.github+json")
	request.Header.Set("User-Agent", "xaligo-aws-definition-sync")
	if rcvr.token != "" {
		request.Header.Set("Authorization", "Bearer "+rcvr.token)
	}
	response, err := rcvr.http.Do(request)
	if err != nil {
		return nil, err
	}
	if response.StatusCode < http.StatusOK || response.StatusCode >= http.StatusMultipleChoices {
		defer response.Body.Close()
		message, _ := io.ReadAll(io.LimitReader(response.Body, 8<<10))
		return nil, fmt.Errorf("GET %s: %s: %s", endpoint, response.Status, strings.TrimSpace(string(message)))
	}
	return response, nil
}

func (rcvr *githubClient) definitions(tarballURL string) ([]definition, error) {
	response, err := rcvr.get(tarballURL)
	if err != nil {
		return nil, fmt.Errorf("download AWS Provider source archive: %w", err)
	}
	defer response.Body.Close()
	gzipReader, err := gzip.NewReader(response.Body)
	if err != nil {
		return nil, fmt.Errorf("open AWS Provider source archive: %w", err)
	}
	defer gzipReader.Close()

	var definitions []definition
	serviceFiles := 0
	functionFiles := 0
	tarReader := tar.NewReader(gzipReader)
	for {
		header, err := tarReader.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read AWS Provider source archive: %w", err)
		}
		if header.Typeflag != tar.TypeReg && header.Typeflag != tar.TypeRegA {
			continue
		}
		service, serviceFile := servicePackagePath(header.Name)
		functionFile := providerFunctionPath(header.Name)
		if !serviceFile && !functionFile {
			continue
		}
		if header.Size < 0 || header.Size > maximumSourceFileLen {
			return nil, fmt.Errorf("refuse unexpectedly large source file %q (%d bytes)", header.Name, header.Size)
		}
		source, err := io.ReadAll(io.LimitReader(tarReader, maximumSourceFileLen+1))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", header.Name, err)
		}
		if len(source) > maximumSourceFileLen {
			return nil, fmt.Errorf("source file %q exceeds %d bytes", header.Name, maximumSourceFileLen)
		}
		if serviceFile {
			found, err := parseServiceDefinitions(header.Name, service, source)
			if err != nil {
				return nil, err
			}
			definitions = append(definitions, found...)
			serviceFiles++
			continue
		}
		found, err := parseFunctionDefinitions(header.Name, source)
		if err != nil {
			return nil, err
		}
		definitions = append(definitions, found...)
		functionFiles++
	}
	if serviceFiles == 0 || functionFiles == 0 {
		return nil, fmt.Errorf("source archive yielded %d service registration files and %d provider function files", serviceFiles, functionFiles)
	}
	return canonicalDefinitions(definitions)
}

func servicePackagePath(name string) (string, bool) {
	parts := strings.Split(filepath.ToSlash(name), "/")
	for index := 0; index+3 < len(parts); index++ {
		if parts[index] == "internal" && parts[index+1] == "service" && parts[index+3] == "service_package_gen.go" && index+4 == len(parts) {
			return parts[index+2], true
		}
	}
	return "", false
}

func providerFunctionPath(name string) bool {
	parts := strings.Split(filepath.ToSlash(name), "/")
	for index := 0; index+2 < len(parts); index++ {
		if parts[index] != "internal" || parts[index+1] != "function" || index+3 != len(parts) {
			continue
		}
		filename := parts[index+2]
		return strings.HasSuffix(filename, ".go") && !strings.HasSuffix(filename, "_test.go")
	}
	return false
}

func parseServiceDefinitions(filename, service string, source []byte) ([]definition, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), filename, source, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", filename, err)
	}
	var definitions []definition
	for _, declaration := range parsed.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Body == nil {
			continue
		}
		kind, ok := registrationKind(function.Name.Name)
		if !ok {
			continue
		}
		ast.Inspect(function.Body, func(node ast.Node) bool {
			field, ok := node.(*ast.KeyValueExpr)
			if !ok {
				return true
			}
			key, ok := field.Key.(*ast.Ident)
			if !ok || key.Name != "TypeName" {
				return true
			}
			literal, ok := field.Value.(*ast.BasicLit)
			if !ok || literal.Kind != token.STRING {
				return true
			}
			typeName, err := strconv.Unquote(literal.Value)
			if err == nil {
				definitions = append(definitions, definition{Kind: kind, Service: service, TypeName: typeName})
			}
			return true
		})
	}
	return definitions, nil
}

func registrationKind(method string) (string, bool) {
	switch {
	case strings.HasSuffix(method, "DataSources"):
		return "data_source", true
	case strings.HasSuffix(method, "ListResources"):
		return "list_resource", true
	case strings.HasSuffix(method, "EphemeralResources"):
		return "ephemeral_resource", true
	case strings.HasSuffix(method, "Actions"):
		return "action", true
	case strings.HasSuffix(method, "Resources"):
		return "resource", true
	default:
		return "", false
	}
}

func parseFunctionDefinitions(filename string, source []byte) ([]definition, error) {
	parsed, err := parser.ParseFile(token.NewFileSet(), filename, source, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", filename, err)
	}
	var definitions []definition
	for _, declaration := range parsed.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != "Metadata" || function.Body == nil {
			continue
		}
		ast.Inspect(function.Body, func(node ast.Node) bool {
			assignment, ok := node.(*ast.AssignStmt)
			if !ok {
				return true
			}
			for index, left := range assignment.Lhs {
				if index >= len(assignment.Rhs) {
					continue
				}
				selector, ok := left.(*ast.SelectorExpr)
				if !ok || selector.Sel.Name != "Name" {
					continue
				}
				literal, ok := assignment.Rhs[index].(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					continue
				}
				name, err := strconv.Unquote(literal.Value)
				if err == nil {
					definitions = append(definitions, definition{Kind: "function", Service: "provider", TypeName: name})
				}
			}
			return true
		})
	}
	return definitions, nil
}

func canonicalDefinitions(input []definition) ([]definition, error) {
	unique := make(map[string]definition, len(input))
	for _, current := range input {
		key := current.Kind + "\x00" + current.TypeName
		if previous, exists := unique[key]; exists && previous.Service != current.Service {
			return nil, fmt.Errorf("definition %s:%s is owned by both %s and %s", current.Kind, current.TypeName, previous.Service, current.Service)
		}
		unique[key] = current
	}
	definitions := make([]definition, 0, len(unique))
	for _, current := range unique {
		definitions = append(definitions, current)
	}
	sort.Slice(definitions, func(left, right int) bool {
		leftKey := definitions[left].Kind + "\x00" + definitions[left].TypeName
		rightKey := definitions[right].Kind + "\x00" + definitions[right].TypeName
		return leftKey < rightKey
	})
	return definitions, nil
}

func validateSnapshot(inventory snapshot) error {
	if inventory.Source != providerSource || inventory.Version == "" || !fullCommitPattern.MatchString(inventory.Commit) || inventory.License != providerLicense {
		return fmt.Errorf("invalid snapshot provenance: source=%q version=%q commit=%q license=%q", inventory.Source, inventory.Version, inventory.Commit, inventory.License)
	}
	allowedKinds := map[string]bool{
		"action": true, "data_source": true, "ephemeral_resource": true,
		"function": true, "list_resource": true, "resource": true,
	}
	counts := make(map[string]int, len(allowedKinds))
	previousKey := ""
	for index, current := range inventory.Definitions {
		if !allowedKinds[current.Kind] || current.Service == "" || current.TypeName == "" {
			return fmt.Errorf("invalid definition at index %d: %#v", index, current)
		}
		if current.Kind == "function" {
			if strings.HasPrefix(current.TypeName, "aws_") {
				return fmt.Errorf("provider function %q unexpectedly has aws_ prefix", current.TypeName)
			}
		} else if !strings.HasPrefix(current.TypeName, "aws_") {
			return fmt.Errorf("%s definition %q has no aws_ prefix", current.Kind, current.TypeName)
		}
		key := current.Kind + "\x00" + current.TypeName
		if key <= previousKey {
			return fmt.Errorf("definitions are not strictly ordered and unique at index %d", index)
		}
		previousKey = key
		counts[current.Kind]++
	}
	for kind := range allowedKinds {
		if counts[kind] == 0 {
			return fmt.Errorf("snapshot contains no %s definitions", kind)
		}
	}
	return nil
}

func readSnapshot(path string) (snapshot, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return snapshot{}, fmt.Errorf("read snapshot %s: %w", path, err)
	}
	var inventory snapshot
	if err := json.Unmarshal(content, &inventory); err != nil {
		return snapshot{}, fmt.Errorf("decode snapshot %s: %w", path, err)
	}
	return inventory, nil
}

func writeInventory(repositoryRoot string, inventory snapshot) error {
	jsonContent, err := json.MarshalIndent(inventory, "", "  ")
	if err != nil {
		return fmt.Errorf("encode snapshot: %w", err)
	}
	jsonContent = append(jsonContent, '\n')
	generated, err := renderGeneratedFiles(inventory)
	if err != nil {
		return err
	}
	if err := writeIfChanged(filepath.Join(repositoryRoot, snapshotRelative), jsonContent); err != nil {
		return err
	}
	return writeGeneratedFiles(repositoryRoot, generated)
}

func renderGeneratedFiles(inventory snapshot) (map[string][]byte, error) {
	groups, err := groupDefinitions(inventory.Definitions)
	if err != nil {
		return nil, err
	}
	files := make(map[string][]byte, len(groups)+2)
	metadata, err := renderMetadata(inventory)
	if err != nil {
		return nil, err
	}
	files[metadataRelative] = metadata
	index, err := renderDefinitionGroups(groups)
	if err != nil {
		return nil, err
	}
	files[groupsRelative] = index
	for _, group := range groups {
		content, err := renderServiceDefinitions(group)
		if err != nil {
			return nil, err
		}
		path := filepath.Join(generatedRootRelative, group.Kind, group.Service+"_definitions_gen.go")
		if _, exists := files[path]; exists {
			return nil, fmt.Errorf("generated path collision: %s", path)
		}
		files[path] = content
	}
	return files, nil
}

func groupDefinitions(definitions []definition) ([]definitionGroup, error) {
	grouped := make(map[string]*definitionGroup)
	for _, current := range definitions {
		if !servicePattern.MatchString(current.Service) {
			return nil, fmt.Errorf("service %q cannot form a generated file and variable", current.Service)
		}
		key := current.Kind + "\x00" + current.Service
		group := grouped[key]
		if group == nil {
			group = &definitionGroup{Kind: current.Kind, Service: current.Service}
			grouped[key] = group
		}
		group.TypeNames = append(group.TypeNames, current.TypeName)
	}
	groups := make([]definitionGroup, 0, len(grouped))
	identifiers := make(map[string]string, len(grouped))
	for _, group := range grouped {
		sort.Strings(group.TypeNames)
		identifier, err := serviceVariable(group.Service)
		if err != nil {
			return nil, err
		}
		identifierKey := group.Kind + "\x00" + identifier
		if previous, exists := identifiers[identifierKey]; exists && previous != group.Service {
			return nil, fmt.Errorf("services %q and %q produce the same variable %s", previous, group.Service, identifier)
		}
		identifiers[identifierKey] = group.Service
		groups = append(groups, *group)
	}
	sort.Slice(groups, func(left, right int) bool {
		leftKey := groups[left].Kind + "\x00" + groups[left].Service
		rightKey := groups[right].Kind + "\x00" + groups[right].Service
		return leftKey < rightKey
	})
	return groups, nil
}

func renderMetadata(inventory snapshot) ([]byte, error) {
	var source bytes.Buffer
	source.WriteString(generatedHeader + "\n")
	source.WriteString("package aws\n\n")
	source.WriteString("const (\n")
	fmt.Fprintf(&source, "\tAWSProviderSource = %q\n", inventory.Source)
	fmt.Fprintf(&source, "\tAWSProviderVersion = %q\n", inventory.Version)
	fmt.Fprintf(&source, "\tAWSProviderCommit = %q\n", inventory.Commit)
	fmt.Fprintf(&source, "\tAWSProviderLicense = %q\n", inventory.License)
	fmt.Fprintf(&source, "\tAWSProviderDefinitionCount = %d\n", len(inventory.Definitions))
	source.WriteString(")\n\n")
	return formatGenerated(source.Bytes(), metadataRelative)
}

func renderDefinitionGroups(groups []definitionGroup) ([]byte, error) {
	var source bytes.Buffer
	source.WriteString(generatedHeader + "\n")
	source.WriteString("package aws\n\n")
	source.WriteString("import (\n")
	kinds := make(map[string]bool, len(definitionKinds))
	for _, group := range groups {
		kinds[group.Kind] = true
	}
	for _, kind := range definitionKinds {
		if !kinds[kind] {
			continue
		}
		fmt.Fprintf(
			&source,
			"\t%s %q\n",
			kindPackageAlias(kind),
			"github.com/xaligo/terraform-provider/internal/entity/aws/"+kind,
		)
	}
	source.WriteString(")\n\n")
	source.WriteString("var providerDefinitionGroups = [...]providerDefinitionGroup{\n")
	for _, group := range groups {
		kind, err := kindIdentifier(group.Kind)
		if err != nil {
			return nil, err
		}
		variable, err := serviceVariable(group.Service)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(
			&source,
			"\t{Kind: %s, Service: %q, TypeNames: %s.%s[:]},\n",
			kind,
			group.Service,
			kindPackageAlias(group.Kind),
			variable,
		)
	}
	source.WriteString("}\n")
	return formatGenerated(source.Bytes(), groupsRelative)
}

func renderServiceDefinitions(group definitionGroup) ([]byte, error) {
	variable, err := serviceVariable(group.Service)
	if err != nil {
		return nil, err
	}
	var source bytes.Buffer
	source.WriteString(generatedHeader + "\n")
	fmt.Fprintf(&source, "package %s\n\n", kindPackageName(group.Kind))
	fmt.Fprintf(&source, "var %s = [...]string{\n", variable)
	for _, typeName := range group.TypeNames {
		fmt.Fprintf(&source, "\t%q,\n", typeName)
	}
	source.WriteString("}\n")
	path := filepath.Join(generatedRootRelative, group.Kind, group.Service+"_definitions_gen.go")
	return formatGenerated(source.Bytes(), path)
}

func formatGenerated(source []byte, path string) ([]byte, error) {
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format generated file %s: %w", path, err)
	}
	return formatted, nil
}

func kindPackageName(kind string) string {
	return strings.ReplaceAll(kind, "_", "")
}

func kindPackageAlias(kind string) string {
	return kindPackageName(kind) + "definitions"
}

func serviceVariable(service string) (string, error) {
	if !servicePattern.MatchString(service) {
		return "", fmt.Errorf("service %q cannot form a Go variable", service)
	}
	parts := strings.Split(service, "_")
	var identifier strings.Builder
	for _, part := range parts {
		identifier.WriteString(strings.ToUpper(part[:1]))
		identifier.WriteString(part[1:])
	}
	identifier.WriteString("Definitions")
	return identifier.String(), nil
}

func checkGeneratedFiles(repositoryRoot string, expected map[string][]byte) error {
	actual, err := managedGeneratedFiles(repositoryRoot)
	if err != nil {
		return err
	}
	differences := make([]string, 0)
	for relative, content := range expected {
		current, err := os.ReadFile(filepath.Join(repositoryRoot, relative))
		if err != nil || !bytes.Equal(current, content) {
			differences = append(differences, relative)
		}
	}
	for _, relative := range actual {
		if _, exists := expected[relative]; !exists {
			differences = append(differences, relative+" (stale)")
		}
	}
	if len(differences) == 0 {
		return nil
	}
	sort.Strings(differences)
	if len(differences) > 10 {
		differences = append(differences[:10], "...")
	}
	return fmt.Errorf("generated AWS definitions differ: %s; run `make aws-definitions-generate`", strings.Join(differences, ", "))
}

func writeGeneratedFiles(repositoryRoot string, expected map[string][]byte) error {
	paths := make([]string, 0, len(expected))
	for relative := range expected {
		paths = append(paths, relative)
	}
	sort.Strings(paths)
	for _, relative := range paths {
		if err := writeIfChanged(filepath.Join(repositoryRoot, relative), expected[relative]); err != nil {
			return err
		}
	}
	actual, err := managedGeneratedFiles(repositoryRoot)
	if err != nil {
		return err
	}
	for _, relative := range actual {
		if _, exists := expected[relative]; exists {
			continue
		}
		path := filepath.Join(repositoryRoot, relative)
		content, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("read stale generated file %s: %w", relative, err)
		}
		if !bytes.HasPrefix(content, []byte(generatedHeader)) {
			return fmt.Errorf("refuse to remove unrecognized generated file %s", relative)
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove stale generated file %s: %w", relative, err)
		}
	}
	return nil
}

func managedGeneratedFiles(repositoryRoot string) ([]string, error) {
	files := make([]string, 0)
	for _, relative := range []string{metadataRelative, groupsRelative, legacyRelative} {
		path := filepath.Join(repositoryRoot, relative)
		info, err := os.Lstat(path)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("inspect generated file %s: %w", relative, err)
		}
		if !info.Mode().IsRegular() {
			return nil, fmt.Errorf("generated path is not a regular file: %s", relative)
		}
		files = append(files, relative)
	}
	for _, kind := range definitionKinds {
		directoryRelative := filepath.Join(generatedRootRelative, kind)
		directory := filepath.Join(repositoryRoot, directoryRelative)
		entries, err := os.ReadDir(directory)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			return nil, fmt.Errorf("read generated directory %s: %w", directoryRelative, err)
		}
		for _, entry := range entries {
			if !strings.HasSuffix(entry.Name(), "_definitions_gen.go") {
				continue
			}
			if entry.IsDir() || entry.Type()&os.ModeSymlink != 0 {
				return nil, fmt.Errorf("generated path is not a regular file: %s", filepath.Join(directoryRelative, entry.Name()))
			}
			files = append(files, filepath.Join(directoryRelative, entry.Name()))
		}
	}
	sort.Strings(files)
	return files, nil
}

func kindIdentifier(kind string) (string, error) {
	switch kind {
	case "action":
		return "DefinitionKindAction", nil
	case "data_source":
		return "DefinitionKindDataSource", nil
	case "ephemeral_resource":
		return "DefinitionKindEphemeralResource", nil
	case "function":
		return "DefinitionKindFunction", nil
	case "list_resource":
		return "DefinitionKindListResource", nil
	case "resource":
		return "DefinitionKindResource", nil
	default:
		return "", fmt.Errorf("unsupported definition kind %q", kind)
	}
}

func writeIfChanged(path string, content []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && bytes.Equal(current, content) {
		return nil
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".aws-definitions-*")
	if err != nil {
		return fmt.Errorf("create temporary file for %s: %w", path, err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return fmt.Errorf("set permissions on temporary file for %s: %w", path, err)
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary file for %s: %w", path, err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary file for %s: %w", path, err)
	}
	if err := os.Rename(temporaryPath, path); err != nil {
		return fmt.Errorf("replace %s: %w", path, err)
	}
	return nil
}
