// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var AmpDefinitions = [...]string{
	"aws_prometheus_default_scraper_configuration",
	"aws_prometheus_workspace",
	"aws_prometheus_workspaces",
}
