// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ApigatewayDefinitions = [...]string{
	"aws_api_gateway_api_key",
	"aws_api_gateway_api_keys",
	"aws_api_gateway_authorizer",
	"aws_api_gateway_authorizers",
	"aws_api_gateway_domain_name",
	"aws_api_gateway_export",
	"aws_api_gateway_resource",
	"aws_api_gateway_rest_api",
	"aws_api_gateway_sdk",
	"aws_api_gateway_vpc_link",
}
