// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Apigatewayv2Definitions = [...]string{
	"aws_apigatewayv2_api",
	"aws_apigatewayv2_apis",
	"aws_apigatewayv2_export",
	"aws_apigatewayv2_vpc_link",
}
