// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var AppconfigDefinitions = [...]string{
	"aws_appconfig_application",
	"aws_appconfig_configuration_profile",
	"aws_appconfig_configuration_profiles",
	"aws_appconfig_environment",
	"aws_appconfig_environments",
}
