// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var AppmeshDefinitions = [...]string{
	"aws_appmesh_gateway_route",
	"aws_appmesh_mesh",
	"aws_appmesh_route",
	"aws_appmesh_virtual_gateway",
	"aws_appmesh_virtual_node",
	"aws_appmesh_virtual_router",
	"aws_appmesh_virtual_service",
}
