// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ArcregionswitchDefinitions = [...]string{
	"aws_arcregionswitch_plan",
	"aws_arcregionswitch_route53_health_checks",
}
