// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var AutoscalingDefinitions = [...]string{
	"aws_autoscaling_group",
	"aws_autoscaling_groups",
	"aws_launch_configuration",
}
