// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var BackupDefinitions = [...]string{
	"aws_backup_framework",
	"aws_backup_plan",
	"aws_backup_report_plan",
	"aws_backup_selection",
	"aws_backup_vault",
}
