// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var BedrockDefinitions = [...]string{
	"aws_bedrock_custom_model",
	"aws_bedrock_custom_models",
	"aws_bedrock_foundation_model",
	"aws_bedrock_foundation_model_agreement_offers",
	"aws_bedrock_foundation_models",
	"aws_bedrock_inference_profile",
	"aws_bedrock_inference_profiles",
	"aws_bedrock_use_case_for_model_access",
}
