// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var CloudfrontDefinitions = [...]string{
	"aws_cloudfront_cache_policy",
	"aws_cloudfront_connection_group",
	"aws_cloudfront_distribution",
	"aws_cloudfront_distribution_tenant",
	"aws_cloudfront_function",
	"aws_cloudfront_log_delivery_canonical_user_id",
	"aws_cloudfront_origin_access_control",
	"aws_cloudfront_origin_access_identities",
	"aws_cloudfront_origin_access_identity",
	"aws_cloudfront_origin_request_policy",
	"aws_cloudfront_realtime_log_config",
	"aws_cloudfront_response_headers_policy",
}
