// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var CloudformationDefinitions = [...]string{
	"aws_cloudformation_export",
	"aws_cloudformation_stack",
	"aws_cloudformation_type",
}
