// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var CodeartifactDefinitions = [...]string{
	"aws_codeartifact_authorization_token",
	"aws_codeartifact_repository_endpoint",
}
