// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var CodecommitDefinitions = [...]string{
	"aws_codecommit_approval_rule_template",
	"aws_codecommit_repository",
}
