// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var CognitoidpDefinitions = [...]string{
	"aws_cognito_user_group",
	"aws_cognito_user_groups",
	"aws_cognito_user_pool",
	"aws_cognito_user_pool_client",
	"aws_cognito_user_pool_clients",
	"aws_cognito_user_pool_signing_certificate",
	"aws_cognito_user_pools",
}
