// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ConnectDefinitions = [...]string{
	"aws_connect_bot_association",
	"aws_connect_contact_flow",
	"aws_connect_contact_flow_module",
	"aws_connect_hours_of_operation",
	"aws_connect_instance",
	"aws_connect_instance_storage_config",
	"aws_connect_lambda_function_association",
	"aws_connect_prompt",
	"aws_connect_queue",
	"aws_connect_quick_connect",
	"aws_connect_routing_profile",
	"aws_connect_security_profile",
	"aws_connect_user",
	"aws_connect_user_hierarchy_group",
	"aws_connect_user_hierarchy_structure",
	"aws_connect_vocabulary",
}
