// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var DevopsguruDefinitions = [...]string{
	"aws_devopsguru_notification_channel",
	"aws_devopsguru_resource_collection",
}
