// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var DirectconnectDefinitions = [...]string{
	"aws_dx_connection",
	"aws_dx_gateway",
	"aws_dx_location",
	"aws_dx_locations",
	"aws_dx_router_configuration",
}
