// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var DmsDefinitions = [...]string{
	"aws_dms_certificate",
	"aws_dms_endpoint",
	"aws_dms_replication_instance",
	"aws_dms_replication_subnet_group",
	"aws_dms_replication_task",
}
