// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var DynamodbDefinitions = [...]string{
	"aws_dynamodb_backups",
	"aws_dynamodb_table",
	"aws_dynamodb_table_item",
	"aws_dynamodb_tables",
}
