// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var EcrDefinitions = [...]string{
	"aws_ecr_authorization_token",
	"aws_ecr_image",
	"aws_ecr_images",
	"aws_ecr_lifecycle_policy_document",
	"aws_ecr_pull_through_cache_rule",
	"aws_ecr_repositories",
	"aws_ecr_repository",
	"aws_ecr_repository_creation_template",
}
