// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var EcsDefinitions = [...]string{
	"aws_ecs_cluster",
	"aws_ecs_clusters",
	"aws_ecs_container_definition",
	"aws_ecs_service",
	"aws_ecs_task_definition",
	"aws_ecs_task_execution",
}
