// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var EfsDefinitions = [...]string{
	"aws_efs_access_point",
	"aws_efs_access_points",
	"aws_efs_file_system",
	"aws_efs_mount_target",
}
