// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var EksDefinitions = [...]string{
	"aws_eks_access_entry",
	"aws_eks_access_policies",
	"aws_eks_addon",
	"aws_eks_addon_version",
	"aws_eks_cluster",
	"aws_eks_cluster_auth",
	"aws_eks_cluster_versions",
	"aws_eks_clusters",
	"aws_eks_node_group",
	"aws_eks_node_groups",
}
