// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ElasticbeanstalkDefinitions = [...]string{
	"aws_elastic_beanstalk_application",
	"aws_elastic_beanstalk_hosted_zone",
	"aws_elastic_beanstalk_solution_stack",
}
