// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ElasticacheDefinitions = [...]string{
	"aws_elasticache_cluster",
	"aws_elasticache_replication_group",
	"aws_elasticache_reserved_cache_node_offering",
	"aws_elasticache_serverless_cache",
	"aws_elasticache_service_update_actions",
	"aws_elasticache_service_updates",
	"aws_elasticache_subnet_group",
	"aws_elasticache_user",
}
