// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Elbv2Definitions = [...]string{
	"aws_alb",
	"aws_alb_listener",
	"aws_alb_target_group",
	"aws_lb",
	"aws_lb_hosted_zone_id",
	"aws_lb_listener",
	"aws_lb_listener_rule",
	"aws_lb_target_group",
	"aws_lb_trust_store",
	"aws_lbs",
}
