// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var EventsDefinitions = [...]string{
	"aws_cloudwatch_event_bus",
	"aws_cloudwatch_event_buses",
	"aws_cloudwatch_event_connection",
	"aws_cloudwatch_event_source",
}
