// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var FsxDefinitions = [...]string{
	"aws_fsx_ontap_file_system",
	"aws_fsx_ontap_storage_virtual_machine",
	"aws_fsx_ontap_storage_virtual_machines",
	"aws_fsx_openzfs_snapshot",
	"aws_fsx_windows_file_system",
}
