// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var GlobalacceleratorDefinitions = [...]string{
	"aws_globalaccelerator_accelerator",
	"aws_globalaccelerator_custom_routing_accelerator",
}
