// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var GlueDefinitions = [...]string{
	"aws_glue_catalog",
	"aws_glue_catalog_table",
	"aws_glue_connection",
	"aws_glue_data_catalog_encryption_settings",
	"aws_glue_registry",
	"aws_glue_script",
}
