// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var IamDefinitions = [...]string{
	"aws_iam_access_keys",
	"aws_iam_account_alias",
	"aws_iam_group",
	"aws_iam_instance_profile",
	"aws_iam_instance_profiles",
	"aws_iam_openid_connect_provider",
	"aws_iam_outbound_web_identity_federation",
	"aws_iam_policy",
	"aws_iam_policy_document",
	"aws_iam_principal_policy_simulation",
	"aws_iam_role",
	"aws_iam_role_policies",
	"aws_iam_role_policy_attachments",
	"aws_iam_roles",
	"aws_iam_saml_provider",
	"aws_iam_server_certificate",
	"aws_iam_session_context",
	"aws_iam_user",
	"aws_iam_user_ssh_key",
	"aws_iam_users",
}
