// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var IdentitystoreDefinitions = [...]string{
	"aws_identitystore_group",
	"aws_identitystore_group_memberships",
	"aws_identitystore_groups",
	"aws_identitystore_user",
	"aws_identitystore_users",
}
