// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ImagebuilderDefinitions = [...]string{
	"aws_imagebuilder_component",
	"aws_imagebuilder_components",
	"aws_imagebuilder_container_recipe",
	"aws_imagebuilder_container_recipes",
	"aws_imagebuilder_distribution_configuration",
	"aws_imagebuilder_distribution_configurations",
	"aws_imagebuilder_image",
	"aws_imagebuilder_image_pipeline",
	"aws_imagebuilder_image_pipelines",
	"aws_imagebuilder_image_recipe",
	"aws_imagebuilder_image_recipes",
	"aws_imagebuilder_infrastructure_configuration",
	"aws_imagebuilder_infrastructure_configurations",
}
