// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var KafkaDefinitions = [...]string{
	"aws_msk_bootstrap_brokers",
	"aws_msk_broker_nodes",
	"aws_msk_cluster",
	"aws_msk_configuration",
	"aws_msk_kafka_version",
	"aws_msk_topic",
	"aws_msk_vpc_connection",
}
