// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var KendraDefinitions = [...]string{
	"aws_kendra_experience",
	"aws_kendra_faq",
	"aws_kendra_index",
	"aws_kendra_query_suggestions_block_list",
	"aws_kendra_thesaurus",
}
