// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var KmsDefinitions = [...]string{
	"aws_kms_alias",
	"aws_kms_ciphertext",
	"aws_kms_custom_key_store",
	"aws_kms_key",
	"aws_kms_public_key",
	"aws_kms_secret",
	"aws_kms_secrets",
}
