// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var LakeformationDefinitions = [...]string{
	"aws_lakeformation_data_lake_settings",
	"aws_lakeformation_permissions",
	"aws_lakeformation_resource",
}
