// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var LambdaDefinitions = [...]string{
	"aws_lambda_alias",
	"aws_lambda_code_signing_config",
	"aws_lambda_function",
	"aws_lambda_function_url",
	"aws_lambda_functions",
	"aws_lambda_invocation",
	"aws_lambda_layer_version",
}
