// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var LicensemanagerDefinitions = [...]string{
	"aws_licensemanager_grants",
	"aws_licensemanager_received_license",
	"aws_licensemanager_received_licenses",
}
