// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var LogsDefinitions = [...]string{
	"aws_cloudwatch_log_data_protection_policy_document",
	"aws_cloudwatch_log_group",
	"aws_cloudwatch_log_groups",
}
