// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var MemorydbDefinitions = [...]string{
	"aws_memorydb_acl",
	"aws_memorydb_cluster",
	"aws_memorydb_parameter_group",
	"aws_memorydb_snapshot",
	"aws_memorydb_subnet_group",
	"aws_memorydb_user",
}
