// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var MetaDefinitions = [...]string{
	"aws_arn",
	"aws_default_tags",
	"aws_ip_ranges",
	"aws_partition",
	"aws_region",
	"aws_regions",
	"aws_service",
	"aws_service_principal",
}
