// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var MqDefinitions = [...]string{
	"aws_mq_broker",
	"aws_mq_broker_engine_types",
	"aws_mq_broker_instance_type_offerings",
}
