// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var NeptuneDefinitions = [...]string{
	"aws_neptune_engine_version",
	"aws_neptune_orderable_db_instance",
}
