// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var NetworkmanagerDefinitions = [...]string{
	"aws_networkmanager_connection",
	"aws_networkmanager_connections",
	"aws_networkmanager_core_network",
	"aws_networkmanager_core_network_policy_document",
	"aws_networkmanager_device",
	"aws_networkmanager_devices",
	"aws_networkmanager_global_network",
	"aws_networkmanager_global_networks",
	"aws_networkmanager_link",
	"aws_networkmanager_links",
	"aws_networkmanager_site",
	"aws_networkmanager_sites",
}
