// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var NetworkfirewallDefinitions = [...]string{
	"aws_networkfirewall_firewall",
	"aws_networkfirewall_firewall_policy",
	"aws_networkfirewall_resource_policy",
}
