// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var OdbDefinitions = [...]string{
	"aws_odb_cloud_autonomous_vm_cluster",
	"aws_odb_cloud_autonomous_vm_clusters",
	"aws_odb_cloud_exadata_infrastructure",
	"aws_odb_cloud_exadata_infrastructures",
	"aws_odb_cloud_vm_cluster",
	"aws_odb_cloud_vm_clusters",
	"aws_odb_db_node",
	"aws_odb_db_nodes",
	"aws_odb_db_server",
	"aws_odb_db_servers",
	"aws_odb_db_system_shapes",
	"aws_odb_gi_versions",
	"aws_odb_iam_role_association",
	"aws_odb_network",
	"aws_odb_network_peering_connection",
	"aws_odb_network_peering_connections",
	"aws_odb_networks",
}
