// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var OpensearchserverlessDefinitions = [...]string{
	"aws_opensearchserverless_access_policy",
	"aws_opensearchserverless_collection",
	"aws_opensearchserverless_collection_group",
	"aws_opensearchserverless_collection_groups",
	"aws_opensearchserverless_lifecycle_policy",
	"aws_opensearchserverless_security_config",
	"aws_opensearchserverless_security_policy",
	"aws_opensearchserverless_vpc_endpoint",
}
