// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var OrganizationsDefinitions = [...]string{
	"aws_organizations_account",
	"aws_organizations_delegated_administrators",
	"aws_organizations_delegated_services",
	"aws_organizations_entity_path",
	"aws_organizations_organization",
	"aws_organizations_organizational_unit",
	"aws_organizations_organizational_unit_child_accounts",
	"aws_organizations_organizational_unit_descendant_accounts",
	"aws_organizations_organizational_unit_descendant_organizational_units",
	"aws_organizations_organizational_units",
	"aws_organizations_policies",
	"aws_organizations_policies_for_target",
	"aws_organizations_policy",
	"aws_organizations_resource_tags",
}
