// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var OutpostsDefinitions = [...]string{
	"aws_outposts_asset",
	"aws_outposts_assets",
	"aws_outposts_outpost",
	"aws_outposts_outpost_instance_type",
	"aws_outposts_outpost_instance_types",
	"aws_outposts_outposts",
	"aws_outposts_site",
	"aws_outposts_sites",
}
