// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var QuicksightDefinitions = [...]string{
	"aws_quicksight_analysis",
	"aws_quicksight_data_set",
	"aws_quicksight_group",
	"aws_quicksight_theme",
	"aws_quicksight_user",
}
