// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var RdsDefinitions = [...]string{
	"aws_db_cluster_snapshot",
	"aws_db_event_categories",
	"aws_db_instance",
	"aws_db_instances",
	"aws_db_parameter_group",
	"aws_db_proxy",
	"aws_db_snapshot",
	"aws_db_subnet_group",
	"aws_rds_certificate",
	"aws_rds_cluster",
	"aws_rds_cluster_parameter_group",
	"aws_rds_clusters",
	"aws_rds_engine_version",
	"aws_rds_global_cluster",
	"aws_rds_orderable_db_instance",
	"aws_rds_reserved_instance_offering",
	"aws_rds_snapshots",
}
