// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var RedshiftserverlessDefinitions = [...]string{
	"aws_redshiftserverless_credentials",
	"aws_redshiftserverless_namespace",
	"aws_redshiftserverless_workgroup",
}
