// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var RedshiftDefinitions = [...]string{
	"aws_redshift_cluster",
	"aws_redshift_cluster_credentials",
	"aws_redshift_data_shares",
	"aws_redshift_orderable_cluster",
	"aws_redshift_producer_data_shares",
	"aws_redshift_subnet_group",
}
