// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Resiliencehubv2Definitions = [...]string{
	"aws_resiliencehubv2_policy",
	"aws_resiliencehubv2_service",
	"aws_resiliencehubv2_system",
}
