// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ResourcegroupstaggingapiDefinitions = [...]string{
	"aws_resourcegroupstaggingapi_required_tags",
	"aws_resourcegroupstaggingapi_resources",
}
