// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Route53Definitions = [...]string{
	"aws_route53_delegation_set",
	"aws_route53_records",
	"aws_route53_traffic_policy_document",
	"aws_route53_zone",
	"aws_route53_zones",
}
