// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Route53profilesDefinitions = [...]string{
	"aws_route53profiles_profile",
	"aws_route53profiles_profiles",
}
