// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var S3Definitions = [...]string{
	"aws_canonical_user_id",
	"aws_s3_bucket",
	"aws_s3_bucket_notification",
	"aws_s3_bucket_object",
	"aws_s3_bucket_object_lock_configuration",
	"aws_s3_bucket_objects",
	"aws_s3_bucket_policy",
	"aws_s3_bucket_replication_configuration",
	"aws_s3_buckets",
	"aws_s3_directory_buckets",
	"aws_s3_object",
	"aws_s3_objects",
}
