// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var S3controlDefinitions = [...]string{
	"aws_s3_access_point",
	"aws_s3_account_public_access_block",
	"aws_s3control_access_points",
	"aws_s3control_multi_region_access_point",
	"aws_s3control_multi_region_access_points",
}
