// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var S3filesDefinitions = [...]string{
	"aws_s3files_access_point",
	"aws_s3files_file_system",
	"aws_s3files_file_systems",
	"aws_s3files_mount_target",
}
