// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SecretsmanagerDefinitions = [...]string{
	"aws_secretsmanager_random_password",
	"aws_secretsmanager_secret",
	"aws_secretsmanager_secret_rotation",
	"aws_secretsmanager_secret_version",
	"aws_secretsmanager_secret_versions",
	"aws_secretsmanager_secrets",
}
