// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SecurityhubDefinitions = [...]string{
	"aws_securityhub_enabled_standards",
	"aws_securityhub_security_controls",
	"aws_securityhub_standards_control_associations",
}
