// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ServicecatalogappregistryDefinitions = [...]string{
	"aws_servicecatalogappregistry_application",
	"aws_servicecatalogappregistry_attribute_group",
	"aws_servicecatalogappregistry_attribute_group_associations",
}
