// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ServicequotasDefinitions = [...]string{
	"aws_servicequotas_service",
	"aws_servicequotas_service_quota",
	"aws_servicequotas_templates",
}
