// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ServicecatalogDefinitions = [...]string{
	"aws_servicecatalog_constraint",
	"aws_servicecatalog_launch_paths",
	"aws_servicecatalog_portfolio",
	"aws_servicecatalog_portfolio_constraints",
	"aws_servicecatalog_product",
	"aws_servicecatalog_provisioning_artifacts",
}
