// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var ServicediscoveryDefinitions = [...]string{
	"aws_service_discovery_dns_namespace",
	"aws_service_discovery_http_namespace",
	"aws_service_discovery_service",
}
