// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SesDefinitions = [...]string{
	"aws_ses_active_receipt_rule_set",
	"aws_ses_domain_identity",
	"aws_ses_email_identity",
}
