// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Sesv2Definitions = [...]string{
	"aws_sesv2_configuration_set",
	"aws_sesv2_dedicated_ip_pool",
	"aws_sesv2_email_identity",
	"aws_sesv2_email_identity_mail_from_attributes",
}
