// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SfnDefinitions = [...]string{
	"aws_sfn_activity",
	"aws_sfn_alias",
	"aws_sfn_state_machine",
	"aws_sfn_state_machine_versions",
}
