// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SsmDefinitions = [...]string{
	"aws_ssm_document",
	"aws_ssm_instances",
	"aws_ssm_maintenance_windows",
	"aws_ssm_parameter",
	"aws_ssm_parameters_by_path",
	"aws_ssm_patch_baseline",
	"aws_ssm_patch_baselines",
}
