// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SsoadminDefinitions = [...]string{
	"aws_ssoadmin_application",
	"aws_ssoadmin_application_assignments",
	"aws_ssoadmin_application_providers",
	"aws_ssoadmin_instances",
	"aws_ssoadmin_permission_set",
	"aws_ssoadmin_permission_sets",
	"aws_ssoadmin_principal_application_assignments",
}
