// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var SyntheticsDefinitions = [...]string{
	"aws_synthetics_runtime_version",
	"aws_synthetics_runtime_versions",
}
