// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var TimestreamwriteDefinitions = [...]string{
	"aws_timestreamwrite_database",
	"aws_timestreamwrite_table",
}
