// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var VpclatticeDefinitions = [...]string{
	"aws_vpclattice_auth_policy",
	"aws_vpclattice_listener",
	"aws_vpclattice_resource_policy",
	"aws_vpclattice_service",
	"aws_vpclattice_service_network",
	"aws_vpclattice_service_network_service_associations",
}
