// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var WafDefinitions = [...]string{
	"aws_waf_ipset",
	"aws_waf_rate_based_rule",
	"aws_waf_rule",
	"aws_waf_subscribed_rule_group",
	"aws_waf_web_acl",
}
