// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var WafregionalDefinitions = [...]string{
	"aws_wafregional_ipset",
	"aws_wafregional_rate_based_rule",
	"aws_wafregional_rule",
	"aws_wafregional_subscribed_rule_group",
	"aws_wafregional_web_acl",
}
