// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var Wafv2Definitions = [...]string{
	"aws_wafv2_ip_set",
	"aws_wafv2_managed_rule_group",
	"aws_wafv2_regex_pattern_set",
	"aws_wafv2_rule_group",
	"aws_wafv2_web_acl",
}
