// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package datasource

var WorkspacesDefinitions = [...]string{
	"aws_workspaces_bundle",
	"aws_workspaces_directory",
	"aws_workspaces_image",
	"aws_workspaces_workspace",
}
