// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AccessanalyzerDefinitions = [...]string{
	"aws_accessanalyzer_analyzer",
	"aws_accessanalyzer_archive_rule",
}
