// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AccountDefinitions = [...]string{
	"aws_account_alternate_contact",
	"aws_account_primary_contact",
	"aws_account_region",
}
