// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AcmpcaDefinitions = [...]string{
	"aws_acmpca_certificate",
	"aws_acmpca_certificate_authority",
	"aws_acmpca_certificate_authority_certificate",
	"aws_acmpca_permission",
	"aws_acmpca_policy",
}
