// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AmpDefinitions = [...]string{
	"aws_prometheus_alert_manager_definition",
	"aws_prometheus_anomaly_detector",
	"aws_prometheus_query_logging_configuration",
	"aws_prometheus_resource_policy",
	"aws_prometheus_rule_group_namespace",
	"aws_prometheus_scraper",
	"aws_prometheus_scraper_logging_configuration",
	"aws_prometheus_workspace",
	"aws_prometheus_workspace_configuration",
}
