// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AmplifyDefinitions = [...]string{
	"aws_amplify_app",
	"aws_amplify_backend_environment",
	"aws_amplify_branch",
	"aws_amplify_domain_association",
	"aws_amplify_webhook",
}
