// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Apigatewayv2Definitions = [...]string{
	"aws_apigatewayv2_api",
	"aws_apigatewayv2_api_mapping",
	"aws_apigatewayv2_authorizer",
	"aws_apigatewayv2_deployment",
	"aws_apigatewayv2_domain_name",
	"aws_apigatewayv2_integration",
	"aws_apigatewayv2_integration_response",
	"aws_apigatewayv2_model",
	"aws_apigatewayv2_route",
	"aws_apigatewayv2_route_response",
	"aws_apigatewayv2_routing_rule",
	"aws_apigatewayv2_stage",
	"aws_apigatewayv2_vpc_link",
}
