// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ApigatewayDefinitions = [...]string{
	"aws_api_gateway_account",
	"aws_api_gateway_api_key",
	"aws_api_gateway_authorizer",
	"aws_api_gateway_base_path_mapping",
	"aws_api_gateway_client_certificate",
	"aws_api_gateway_deployment",
	"aws_api_gateway_documentation_part",
	"aws_api_gateway_documentation_version",
	"aws_api_gateway_domain_name",
	"aws_api_gateway_domain_name_access_association",
	"aws_api_gateway_gateway_response",
	"aws_api_gateway_integration",
	"aws_api_gateway_integration_response",
	"aws_api_gateway_method",
	"aws_api_gateway_method_response",
	"aws_api_gateway_method_settings",
	"aws_api_gateway_model",
	"aws_api_gateway_request_validator",
	"aws_api_gateway_resource",
	"aws_api_gateway_rest_api",
	"aws_api_gateway_rest_api_policy",
	"aws_api_gateway_rest_api_put",
	"aws_api_gateway_stage",
	"aws_api_gateway_usage_plan",
	"aws_api_gateway_usage_plan_key",
	"aws_api_gateway_vpc_link",
}
