// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppautoscalingDefinitions = [...]string{
	"aws_appautoscaling_policy",
	"aws_appautoscaling_scheduled_action",
	"aws_appautoscaling_target",
}
