// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppconfigDefinitions = [...]string{
	"aws_appconfig_application",
	"aws_appconfig_configuration_profile",
	"aws_appconfig_deployment",
	"aws_appconfig_deployment_strategy",
	"aws_appconfig_environment",
	"aws_appconfig_extension",
	"aws_appconfig_extension_association",
	"aws_appconfig_hosted_configuration_version",
}
