// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppfabricDefinitions = [...]string{
	"aws_appfabric_app_authorization",
	"aws_appfabric_app_authorization_connection",
	"aws_appfabric_app_bundle",
	"aws_appfabric_ingestion",
	"aws_appfabric_ingestion_destination",
}
