// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppintegrationsDefinitions = [...]string{
	"aws_appintegrations_data_integration",
	"aws_appintegrations_event_integration",
}
