// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ApprunnerDefinitions = [...]string{
	"aws_apprunner_auto_scaling_configuration_version",
	"aws_apprunner_connection",
	"aws_apprunner_custom_domain_association",
	"aws_apprunner_default_auto_scaling_configuration_version",
	"aws_apprunner_deployment",
	"aws_apprunner_observability_configuration",
	"aws_apprunner_service",
	"aws_apprunner_vpc_connector",
	"aws_apprunner_vpc_ingress_connection",
}
