// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppstreamDefinitions = [...]string{
	"aws_appstream_directory_config",
	"aws_appstream_fleet",
	"aws_appstream_fleet_stack_association",
	"aws_appstream_image_builder",
	"aws_appstream_stack",
	"aws_appstream_user",
	"aws_appstream_user_stack_association",
}
