// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AppsyncDefinitions = [...]string{
	"aws_appsync_api",
	"aws_appsync_api_cache",
	"aws_appsync_api_key",
	"aws_appsync_channel_namespace",
	"aws_appsync_datasource",
	"aws_appsync_domain_name",
	"aws_appsync_domain_name_api_association",
	"aws_appsync_function",
	"aws_appsync_graphql_api",
	"aws_appsync_resolver",
	"aws_appsync_source_api_association",
	"aws_appsync_type",
}
