// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ArczonalshiftDefinitions = [...]string{
	"aws_arczonalshift_autoshift_observer_notification_status",
	"aws_arczonalshift_zonal_autoshift_configuration",
}
