// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AthenaDefinitions = [...]string{
	"aws_athena_capacity_reservation",
	"aws_athena_data_catalog",
	"aws_athena_database",
	"aws_athena_named_query",
	"aws_athena_prepared_statement",
	"aws_athena_workgroup",
}
