// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AuditmanagerDefinitions = [...]string{
	"aws_auditmanager_account_registration",
	"aws_auditmanager_assessment",
	"aws_auditmanager_assessment_delegation",
	"aws_auditmanager_assessment_report",
	"aws_auditmanager_control",
	"aws_auditmanager_framework",
	"aws_auditmanager_framework_share",
	"aws_auditmanager_organization_admin_account_registration",
}
