// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var AutoscalingDefinitions = [...]string{
	"aws_autoscaling_attachment",
	"aws_autoscaling_group",
	"aws_autoscaling_group_tag",
	"aws_autoscaling_lifecycle_hook",
	"aws_autoscaling_notification",
	"aws_autoscaling_policy",
	"aws_autoscaling_schedule",
	"aws_autoscaling_traffic_source_attachment",
	"aws_launch_configuration",
}
