// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var BackupDefinitions = [...]string{
	"aws_backup_framework",
	"aws_backup_global_settings",
	"aws_backup_logically_air_gapped_vault",
	"aws_backup_plan",
	"aws_backup_region_settings",
	"aws_backup_report_plan",
	"aws_backup_restore_testing_plan",
	"aws_backup_restore_testing_selection",
	"aws_backup_selection",
	"aws_backup_vault",
	"aws_backup_vault_lock_configuration",
	"aws_backup_vault_notifications",
	"aws_backup_vault_policy",
}
