// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var BatchDefinitions = [...]string{
	"aws_batch_compute_environment",
	"aws_batch_job_definition",
	"aws_batch_job_queue",
	"aws_batch_scheduling_policy",
}
