// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var BedrockDefinitions = [...]string{
	"aws_bedrock_custom_model",
	"aws_bedrock_evaluation_job",
	"aws_bedrock_foundation_model_agreement",
	"aws_bedrock_guardrail",
	"aws_bedrock_guardrail_version",
	"aws_bedrock_inference_profile",
	"aws_bedrock_model_invocation_logging_configuration",
	"aws_bedrock_provisioned_model_throughput",
	"aws_bedrock_use_case_for_model_access",
}
