// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var BedrockagentcoreDefinitions = [...]string{
	"aws_bedrockagentcore_agent_runtime",
	"aws_bedrockagentcore_agent_runtime_endpoint",
	"aws_bedrockagentcore_api_key_credential_provider",
	"aws_bedrockagentcore_browser",
	"aws_bedrockagentcore_browser_profile",
	"aws_bedrockagentcore_code_interpreter",
	"aws_bedrockagentcore_evaluator",
	"aws_bedrockagentcore_gateway",
	"aws_bedrockagentcore_gateway_rule",
	"aws_bedrockagentcore_gateway_target",
	"aws_bedrockagentcore_harness",
	"aws_bedrockagentcore_memory",
	"aws_bedrockagentcore_memory_strategy",
	"aws_bedrockagentcore_oauth2_credential_provider",
	"aws_bedrockagentcore_online_evaluation_config",
	"aws_bedrockagentcore_policy",
	"aws_bedrockagentcore_policy_engine",
	"aws_bedrockagentcore_registry",
	"aws_bedrockagentcore_resource_policy",
	"aws_bedrockagentcore_token_vault_cmk",
	"aws_bedrockagentcore_workload_identity",
}
