// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var BedrockagentDefinitions = [...]string{
	"aws_bedrockagent_agent",
	"aws_bedrockagent_agent_action_group",
	"aws_bedrockagent_agent_alias",
	"aws_bedrockagent_agent_collaborator",
	"aws_bedrockagent_agent_knowledge_base_association",
	"aws_bedrockagent_data_source",
	"aws_bedrockagent_flow",
	"aws_bedrockagent_knowledge_base",
	"aws_bedrockagent_prompt",
}
