// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CeDefinitions = [...]string{
	"aws_ce_anomaly_monitor",
	"aws_ce_anomaly_subscription",
	"aws_ce_cost_allocation_tag",
	"aws_ce_cost_category",
}
