// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ChatbotDefinitions = [...]string{
	"aws_chatbot_slack_channel_configuration",
	"aws_chatbot_teams_channel_configuration",
}
