// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ChimesdkvoiceDefinitions = [...]string{
	"aws_chimesdkvoice_global_settings",
	"aws_chimesdkvoice_sip_media_application",
	"aws_chimesdkvoice_sip_rule",
	"aws_chimesdkvoice_voice_profile_domain",
}
