// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ChimesdkmediapipelinesDefinitions = [...]string{
	"aws_chimesdkmediapipelines_media_insights_pipeline_configuration",
}
