// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ChimeDefinitions = [...]string{
	"aws_chime_voice_connector",
	"aws_chime_voice_connector_group",
	"aws_chime_voice_connector_logging",
	"aws_chime_voice_connector_origination",
	"aws_chime_voice_connector_streaming",
	"aws_chime_voice_connector_termination",
	"aws_chime_voice_connector_termination_credentials",
}
