// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CleanroomsDefinitions = [...]string{
	"aws_cleanrooms_collaboration",
	"aws_cleanrooms_configured_table",
	"aws_cleanrooms_membership",
}
