// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudwatchDefinitions = [...]string{
	"aws_cloudwatch_alarm_mute_rule",
	"aws_cloudwatch_composite_alarm",
	"aws_cloudwatch_contributor_insight_rule",
	"aws_cloudwatch_contributor_managed_insight_rule",
	"aws_cloudwatch_dashboard",
	"aws_cloudwatch_metric_alarm",
	"aws_cloudwatch_metric_stream",
	"aws_cloudwatch_otel_enrichment",
}
