// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudfrontDefinitions = [...]string{
	"aws_cloudfront_anycast_ip_list",
	"aws_cloudfront_cache_policy",
	"aws_cloudfront_connection_function",
	"aws_cloudfront_connection_group",
	"aws_cloudfront_continuous_deployment_policy",
	"aws_cloudfront_distribution",
	"aws_cloudfront_distribution_tenant",
	"aws_cloudfront_field_level_encryption_config",
	"aws_cloudfront_field_level_encryption_profile",
	"aws_cloudfront_function",
	"aws_cloudfront_key_group",
	"aws_cloudfront_key_value_store",
	"aws_cloudfront_monitoring_subscription",
	"aws_cloudfront_multitenant_distribution",
	"aws_cloudfront_origin_access_control",
	"aws_cloudfront_origin_access_identity",
	"aws_cloudfront_origin_request_policy",
	"aws_cloudfront_public_key",
	"aws_cloudfront_realtime_log_config",
	"aws_cloudfront_response_headers_policy",
	"aws_cloudfront_trust_store",
	"aws_cloudfront_vpc_origin",
}
