// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudformationDefinitions = [...]string{
	"aws_cloudformation_stack",
	"aws_cloudformation_stack_instances",
	"aws_cloudformation_stack_set",
	"aws_cloudformation_stack_set_instance",
	"aws_cloudformation_type",
}
