// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudtrailDefinitions = [...]string{
	"aws_cloudtrail",
	"aws_cloudtrail_event_data_store",
	"aws_cloudtrail_organization_delegated_admin_account",
}
