// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudfrontkeyvaluestoreDefinitions = [...]string{
	"aws_cloudfrontkeyvaluestore_key",
	"aws_cloudfrontkeyvaluestore_keys_exclusive",
}
