// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CloudsearchDefinitions = [...]string{
	"aws_cloudsearch_domain",
	"aws_cloudsearch_domain_service_access_policy",
}
