// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodestarconnectionsDefinitions = [...]string{
	"aws_codestarconnections_connection",
	"aws_codestarconnections_host",
}
