// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodepipelineDefinitions = [...]string{
	"aws_codepipeline",
	"aws_codepipeline_custom_action_type",
	"aws_codepipeline_webhook",
}
