// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodebuildDefinitions = [...]string{
	"aws_codebuild_fleet",
	"aws_codebuild_project",
	"aws_codebuild_report_group",
	"aws_codebuild_resource_policy",
	"aws_codebuild_source_credential",
	"aws_codebuild_webhook",
}
