// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodeartifactDefinitions = [...]string{
	"aws_codeartifact_domain",
	"aws_codeartifact_domain_permissions_policy",
	"aws_codeartifact_repository",
	"aws_codeartifact_repository_permissions_policy",
}
