// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodecommitDefinitions = [...]string{
	"aws_codecommit_approval_rule_template",
	"aws_codecommit_approval_rule_template_association",
	"aws_codecommit_repository",
	"aws_codecommit_trigger",
}
