// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodeconnectionsDefinitions = [...]string{
	"aws_codeconnections_connection",
	"aws_codeconnections_host",
}
