// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CodecatalystDefinitions = [...]string{
	"aws_codecatalyst_dev_environment",
	"aws_codecatalyst_project",
	"aws_codecatalyst_source_repository",
}
