// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CognitoidpDefinitions = [...]string{
	"aws_cognito_identity_provider",
	"aws_cognito_log_delivery_configuration",
	"aws_cognito_managed_login_branding",
	"aws_cognito_managed_user_pool_client",
	"aws_cognito_resource_server",
	"aws_cognito_risk_configuration",
	"aws_cognito_user",
	"aws_cognito_user_group",
	"aws_cognito_user_in_group",
	"aws_cognito_user_pool",
	"aws_cognito_user_pool_client",
	"aws_cognito_user_pool_domain",
	"aws_cognito_user_pool_ui_customization",
}
