// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CognitoidentityDefinitions = [...]string{
	"aws_cognito_identity_pool",
	"aws_cognito_identity_pool_provider_principal_tag",
	"aws_cognito_identity_pool_roles_attachment",
}
