// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ComputeoptimizerDefinitions = [...]string{
	"aws_computeoptimizer_enrollment_status",
	"aws_computeoptimizer_recommendation_preferences",
}
