// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ComprehendDefinitions = [...]string{
	"aws_comprehend_document_classifier",
	"aws_comprehend_entity_recognizer",
}
