// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ConfigserviceDefinitions = [...]string{
	"aws_config_aggregate_authorization",
	"aws_config_config_rule",
	"aws_config_configuration_aggregator",
	"aws_config_configuration_recorder",
	"aws_config_configuration_recorder_status",
	"aws_config_conformance_pack",
	"aws_config_delivery_channel",
	"aws_config_organization_conformance_pack",
	"aws_config_organization_custom_policy_rule",
	"aws_config_organization_custom_rule",
	"aws_config_organization_managed_rule",
	"aws_config_remediation_configuration",
	"aws_config_retention_configuration",
}
