// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ControltowerDefinitions = [...]string{
	"aws_controltower_baseline",
	"aws_controltower_control",
	"aws_controltower_landing_zone",
}
