// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CostoptimizationhubDefinitions = [...]string{
	"aws_costoptimizationhub_enrollment_status",
	"aws_costoptimizationhub_preferences",
}
