// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var CustomerprofilesDefinitions = [...]string{
	"aws_customerprofiles_domain",
	"aws_customerprofiles_profile",
}
