// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DatapipelineDefinitions = [...]string{
	"aws_datapipeline_pipeline",
	"aws_datapipeline_pipeline_definition",
}
