// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DatazoneDefinitions = [...]string{
	"aws_datazone_asset_type",
	"aws_datazone_domain",
	"aws_datazone_environment",
	"aws_datazone_environment_blueprint_configuration",
	"aws_datazone_environment_profile",
	"aws_datazone_form_type",
	"aws_datazone_glossary",
	"aws_datazone_glossary_term",
	"aws_datazone_policy_grant",
	"aws_datazone_project",
	"aws_datazone_user_profile",
}
