// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DataexchangeDefinitions = [...]string{
	"aws_dataexchange_data_set",
	"aws_dataexchange_event_action",
	"aws_dataexchange_revision",
	"aws_dataexchange_revision_assets",
}
