// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DaxDefinitions = [...]string{
	"aws_dax_cluster",
	"aws_dax_parameter_group",
	"aws_dax_subnet_group",
}
