// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DeployDefinitions = [...]string{
	"aws_codedeploy_app",
	"aws_codedeploy_deployment_config",
	"aws_codedeploy_deployment_group",
}
