// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DetectiveDefinitions = [...]string{
	"aws_detective_graph",
	"aws_detective_invitation_accepter",
	"aws_detective_member",
	"aws_detective_organization_admin_account",
	"aws_detective_organization_configuration",
}
