// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DevicefarmDefinitions = [...]string{
	"aws_devicefarm_device_pool",
	"aws_devicefarm_instance_profile",
	"aws_devicefarm_network_profile",
	"aws_devicefarm_project",
	"aws_devicefarm_test_grid_project",
	"aws_devicefarm_upload",
}
