// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DevopsguruDefinitions = [...]string{
	"aws_devopsguru_event_sources_config",
	"aws_devopsguru_notification_channel",
	"aws_devopsguru_resource_collection",
	"aws_devopsguru_service_integration",
}
