// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DirectconnectDefinitions = [...]string{
	"aws_dx_bgp_peer",
	"aws_dx_connection",
	"aws_dx_connection_association",
	"aws_dx_connection_confirmation",
	"aws_dx_gateway",
	"aws_dx_gateway_association",
	"aws_dx_gateway_association_proposal",
	"aws_dx_hosted_connection",
	"aws_dx_hosted_private_virtual_interface",
	"aws_dx_hosted_private_virtual_interface_accepter",
	"aws_dx_hosted_public_virtual_interface",
	"aws_dx_hosted_public_virtual_interface_accepter",
	"aws_dx_hosted_transit_virtual_interface",
	"aws_dx_hosted_transit_virtual_interface_accepter",
	"aws_dx_lag",
	"aws_dx_macsec_key_association",
	"aws_dx_private_virtual_interface",
	"aws_dx_public_virtual_interface",
	"aws_dx_transit_virtual_interface",
}
