// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DocdbDefinitions = [...]string{
	"aws_docdb_cluster",
	"aws_docdb_cluster_instance",
	"aws_docdb_cluster_parameter_group",
	"aws_docdb_cluster_snapshot",
	"aws_docdb_event_subscription",
	"aws_docdb_global_cluster",
	"aws_docdb_subnet_group",
}
