// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DsDefinitions = [...]string{
	"aws_directory_service_conditional_forwarder",
	"aws_directory_service_directory",
	"aws_directory_service_log_subscription",
	"aws_directory_service_radius_settings",
	"aws_directory_service_region",
	"aws_directory_service_shared_directory",
	"aws_directory_service_shared_directory_accepter",
	"aws_directory_service_trust",
}
