// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DsqlDefinitions = [...]string{
	"aws_dsql_cluster",
	"aws_dsql_cluster_peering",
	"aws_dsql_cluster_policy",
}
