// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var DynamodbDefinitions = [...]string{
	"aws_dynamodb_contributor_insights",
	"aws_dynamodb_global_secondary_index",
	"aws_dynamodb_global_table",
	"aws_dynamodb_kinesis_streaming_destination",
	"aws_dynamodb_resource_policy",
	"aws_dynamodb_table",
	"aws_dynamodb_table_export",
	"aws_dynamodb_table_item",
	"aws_dynamodb_table_replica",
	"aws_dynamodb_tag",
}
