// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EcrDefinitions = [...]string{
	"aws_ecr_account_setting",
	"aws_ecr_lifecycle_policy",
	"aws_ecr_pull_through_cache_rule",
	"aws_ecr_pull_time_update_exclusion",
	"aws_ecr_registry_policy",
	"aws_ecr_registry_scanning_configuration",
	"aws_ecr_replication_configuration",
	"aws_ecr_repository",
	"aws_ecr_repository_creation_template",
	"aws_ecr_repository_policy",
}
