// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EcsDefinitions = [...]string{
	"aws_ecs_account_setting_default",
	"aws_ecs_capacity_provider",
	"aws_ecs_cluster",
	"aws_ecs_cluster_capacity_providers",
	"aws_ecs_daemon",
	"aws_ecs_daemon_task_definition",
	"aws_ecs_express_gateway_service",
	"aws_ecs_service",
	"aws_ecs_tag",
	"aws_ecs_task_definition",
	"aws_ecs_task_set",
}
