// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EfsDefinitions = [...]string{
	"aws_efs_access_point",
	"aws_efs_backup_policy",
	"aws_efs_file_system",
	"aws_efs_file_system_policy",
	"aws_efs_mount_target",
	"aws_efs_replication_configuration",
}
