// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EksDefinitions = [...]string{
	"aws_eks_access_entry",
	"aws_eks_access_policy_association",
	"aws_eks_addon",
	"aws_eks_capability",
	"aws_eks_cluster",
	"aws_eks_fargate_profile",
	"aws_eks_identity_provider_config",
	"aws_eks_node_group",
	"aws_eks_pod_identity_association",
}
