// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ElasticacheDefinitions = [...]string{
	"aws_elasticache_cluster",
	"aws_elasticache_global_replication_group",
	"aws_elasticache_parameter_group",
	"aws_elasticache_replication_group",
	"aws_elasticache_reserved_cache_node",
	"aws_elasticache_serverless_cache",
	"aws_elasticache_subnet_group",
	"aws_elasticache_user",
	"aws_elasticache_user_group",
	"aws_elasticache_user_group_association",
}
