// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ElasticbeanstalkDefinitions = [...]string{
	"aws_elastic_beanstalk_application",
	"aws_elastic_beanstalk_application_version",
	"aws_elastic_beanstalk_configuration_template",
	"aws_elastic_beanstalk_environment",
}
