// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ElasticsearchDefinitions = [...]string{
	"aws_elasticsearch_domain",
	"aws_elasticsearch_domain_policy",
	"aws_elasticsearch_domain_saml_options",
	"aws_elasticsearch_vpc_endpoint",
}
