// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ElastictranscoderDefinitions = [...]string{
	"aws_elastictranscoder_pipeline",
	"aws_elastictranscoder_preset",
}
