// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ElbDefinitions = [...]string{
	"aws_app_cookie_stickiness_policy",
	"aws_elb",
	"aws_elb_attachment",
	"aws_lb_cookie_stickiness_policy",
	"aws_lb_ssl_negotiation_policy",
	"aws_load_balancer_backend_server_policy",
	"aws_load_balancer_listener_policy",
	"aws_load_balancer_policy",
	"aws_proxy_protocol_policy",
}
