// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Elbv2Definitions = [...]string{
	"aws_alb",
	"aws_alb_listener",
	"aws_alb_listener_certificate",
	"aws_alb_listener_rule",
	"aws_alb_target_group",
	"aws_alb_target_group_attachment",
	"aws_lb",
	"aws_lb_listener",
	"aws_lb_listener_certificate",
	"aws_lb_listener_rule",
	"aws_lb_target_group",
	"aws_lb_target_group_attachment",
	"aws_lb_trust_store",
	"aws_lb_trust_store_revocation",
}
