// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EmrDefinitions = [...]string{
	"aws_emr_block_public_access_configuration",
	"aws_emr_cluster",
	"aws_emr_instance_fleet",
	"aws_emr_instance_group",
	"aws_emr_managed_scaling_policy",
	"aws_emr_security_configuration",
	"aws_emr_studio",
	"aws_emr_studio_session_mapping",
}
