// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EmrcontainersDefinitions = [...]string{
	"aws_emrcontainers_job_template",
	"aws_emrcontainers_virtual_cluster",
}
