// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EventsDefinitions = [...]string{
	"aws_cloudwatch_event_api_destination",
	"aws_cloudwatch_event_archive",
	"aws_cloudwatch_event_bus",
	"aws_cloudwatch_event_bus_policy",
	"aws_cloudwatch_event_connection",
	"aws_cloudwatch_event_endpoint",
	"aws_cloudwatch_event_permission",
	"aws_cloudwatch_event_rule",
	"aws_cloudwatch_event_target",
}
