// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var EvidentlyDefinitions = [...]string{
	"aws_evidently_feature",
	"aws_evidently_launch",
	"aws_evidently_project",
	"aws_evidently_segment",
}
