// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var FinspaceDefinitions = [...]string{
	"aws_finspace_kx_cluster",
	"aws_finspace_kx_database",
	"aws_finspace_kx_dataview",
	"aws_finspace_kx_environment",
	"aws_finspace_kx_scaling_group",
	"aws_finspace_kx_user",
	"aws_finspace_kx_volume",
}
