// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var FisDefinitions = [...]string{
	"aws_fis_experiment_template",
	"aws_fis_target_account_configuration",
}
