// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var FsxDefinitions = [...]string{
	"aws_fsx_backup",
	"aws_fsx_data_repository_association",
	"aws_fsx_file_cache",
	"aws_fsx_lustre_file_system",
	"aws_fsx_ontap_file_system",
	"aws_fsx_ontap_storage_virtual_machine",
	"aws_fsx_ontap_volume",
	"aws_fsx_openzfs_file_system",
	"aws_fsx_openzfs_snapshot",
	"aws_fsx_openzfs_volume",
	"aws_fsx_s3_access_point_attachment",
	"aws_fsx_windows_file_system",
}
