// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var GameliftDefinitions = [...]string{
	"aws_gamelift_alias",
	"aws_gamelift_build",
	"aws_gamelift_fleet",
	"aws_gamelift_game_server_group",
	"aws_gamelift_game_session_queue",
	"aws_gamelift_script",
}
