// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var GlobalacceleratorDefinitions = [...]string{
	"aws_globalaccelerator_accelerator",
	"aws_globalaccelerator_cross_account_attachment",
	"aws_globalaccelerator_custom_routing_accelerator",
	"aws_globalaccelerator_custom_routing_endpoint_group",
	"aws_globalaccelerator_custom_routing_listener",
	"aws_globalaccelerator_endpoint_group",
	"aws_globalaccelerator_listener",
}
