// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var GlueDefinitions = [...]string{
	"aws_glue_catalog",
	"aws_glue_catalog_database",
	"aws_glue_catalog_table",
	"aws_glue_catalog_table_optimizer",
	"aws_glue_classifier",
	"aws_glue_connection",
	"aws_glue_crawler",
	"aws_glue_data_catalog_encryption_settings",
	"aws_glue_data_quality_ruleset",
	"aws_glue_dev_endpoint",
	"aws_glue_job",
	"aws_glue_ml_transform",
	"aws_glue_partition",
	"aws_glue_partition_index",
	"aws_glue_registry",
	"aws_glue_resource_policy",
	"aws_glue_schema",
	"aws_glue_security_configuration",
	"aws_glue_trigger",
	"aws_glue_user_defined_function",
	"aws_glue_workflow",
}
