// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var GrafanaDefinitions = [...]string{
	"aws_grafana_license_association",
	"aws_grafana_role_association",
	"aws_grafana_workspace",
	"aws_grafana_workspace_api_key",
	"aws_grafana_workspace_saml_configuration",
	"aws_grafana_workspace_service_account",
	"aws_grafana_workspace_service_account_token",
}
