// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var GuarddutyDefinitions = [...]string{
	"aws_guardduty_detector",
	"aws_guardduty_detector_feature",
	"aws_guardduty_filter",
	"aws_guardduty_invite_accepter",
	"aws_guardduty_ipset",
	"aws_guardduty_malware_protection_plan",
	"aws_guardduty_member",
	"aws_guardduty_member_detector_feature",
	"aws_guardduty_organization_admin_account",
	"aws_guardduty_organization_configuration",
	"aws_guardduty_organization_configuration_feature",
	"aws_guardduty_publishing_destination",
	"aws_guardduty_threatintelset",
}
