// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var IdentitystoreDefinitions = [...]string{
	"aws_identitystore_group",
	"aws_identitystore_group_membership",
	"aws_identitystore_user",
}
