// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Inspector2Definitions = [...]string{
	"aws_inspector2_delegated_admin_account",
	"aws_inspector2_enabler",
	"aws_inspector2_filter",
	"aws_inspector2_member_association",
	"aws_inspector2_organization_configuration",
}
