// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var InspectorDefinitions = [...]string{
	"aws_inspector_assessment_target",
	"aws_inspector_assessment_template",
	"aws_inspector_resource_group",
}
