// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var IotDefinitions = [...]string{
	"aws_iot_authorizer",
	"aws_iot_billing_group",
	"aws_iot_ca_certificate",
	"aws_iot_certificate",
	"aws_iot_domain_configuration",
	"aws_iot_event_configurations",
	"aws_iot_indexing_configuration",
	"aws_iot_logging_options",
	"aws_iot_policy",
	"aws_iot_policy_attachment",
	"aws_iot_provisioning_template",
	"aws_iot_role_alias",
	"aws_iot_thing",
	"aws_iot_thing_group",
	"aws_iot_thing_group_membership",
	"aws_iot_thing_principal_attachment",
	"aws_iot_thing_type",
	"aws_iot_topic_rule",
	"aws_iot_topic_rule_destination",
}
