// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var IvsDefinitions = [...]string{
	"aws_ivs_channel",
	"aws_ivs_playback_key_pair",
	"aws_ivs_recording_configuration",
}
