// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var KafkaconnectDefinitions = [...]string{
	"aws_mskconnect_connector",
	"aws_mskconnect_custom_plugin",
	"aws_mskconnect_worker_configuration",
}
