// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var KafkaDefinitions = [...]string{
	"aws_msk_cluster",
	"aws_msk_cluster_policy",
	"aws_msk_configuration",
	"aws_msk_replicator",
	"aws_msk_scram_secret_association",
	"aws_msk_serverless_cluster",
	"aws_msk_single_scram_secret_association",
	"aws_msk_topic",
	"aws_msk_vpc_connection",
}
