// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var KinesisDefinitions = [...]string{
	"aws_kinesis_account_settings",
	"aws_kinesis_resource_policy",
	"aws_kinesis_stream",
	"aws_kinesis_stream_consumer",
}
