// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Kinesisanalyticsv2Definitions = [...]string{
	"aws_kinesisanalyticsv2_application",
	"aws_kinesisanalyticsv2_application_snapshot",
}
