// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var KmsDefinitions = [...]string{
	"aws_kms_alias",
	"aws_kms_ciphertext",
	"aws_kms_custom_key_store",
	"aws_kms_external_key",
	"aws_kms_grant",
	"aws_kms_key",
	"aws_kms_key_policy",
	"aws_kms_replica_external_key",
	"aws_kms_replica_key",
}
