// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LakeformationDefinitions = [...]string{
	"aws_lakeformation_data_cells_filter",
	"aws_lakeformation_data_lake_settings",
	"aws_lakeformation_identity_center_configuration",
	"aws_lakeformation_lf_tag",
	"aws_lakeformation_lf_tag_expression",
	"aws_lakeformation_opt_in",
	"aws_lakeformation_permissions",
	"aws_lakeformation_resource",
	"aws_lakeformation_resource_lf_tag",
	"aws_lakeformation_resource_lf_tags",
}
