// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LambdaDefinitions = [...]string{
	"aws_lambda_alias",
	"aws_lambda_capacity_provider",
	"aws_lambda_code_signing_config",
	"aws_lambda_event_source_mapping",
	"aws_lambda_function",
	"aws_lambda_function_event_invoke_config",
	"aws_lambda_function_recursion_config",
	"aws_lambda_function_scaling_config",
	"aws_lambda_function_url",
	"aws_lambda_invocation",
	"aws_lambda_layer_version",
	"aws_lambda_layer_version_permission",
	"aws_lambda_permission",
	"aws_lambda_provisioned_concurrency_config",
	"aws_lambda_runtime_management_config",
}
