// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LexmodelsDefinitions = [...]string{
	"aws_lex_bot",
	"aws_lex_bot_alias",
	"aws_lex_intent",
	"aws_lex_slot_type",
}
