// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Lexv2modelsDefinitions = [...]string{
	"aws_lexv2models_bot",
	"aws_lexv2models_bot_locale",
	"aws_lexv2models_bot_version",
	"aws_lexv2models_intent",
	"aws_lexv2models_slot",
	"aws_lexv2models_slot_type",
}
