// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LicensemanagerDefinitions = [...]string{
	"aws_licensemanager_association",
	"aws_licensemanager_grant",
	"aws_licensemanager_grant_accepter",
	"aws_licensemanager_license_configuration",
}
