// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LightsailDefinitions = [...]string{
	"aws_lightsail_bucket",
	"aws_lightsail_bucket_access_key",
	"aws_lightsail_bucket_resource_access",
	"aws_lightsail_certificate",
	"aws_lightsail_container_service",
	"aws_lightsail_container_service_deployment_version",
	"aws_lightsail_database",
	"aws_lightsail_disk",
	"aws_lightsail_disk_attachment",
	"aws_lightsail_distribution",
	"aws_lightsail_domain",
	"aws_lightsail_domain_entry",
	"aws_lightsail_instance",
	"aws_lightsail_instance_public_ports",
	"aws_lightsail_key_pair",
	"aws_lightsail_lb",
	"aws_lightsail_lb_attachment",
	"aws_lightsail_lb_certificate",
	"aws_lightsail_lb_certificate_attachment",
	"aws_lightsail_lb_https_redirection_policy",
	"aws_lightsail_lb_stickiness_policy",
	"aws_lightsail_static_ip",
	"aws_lightsail_static_ip_attachment",
}
