// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LocationDefinitions = [...]string{
	"aws_location_geofence_collection",
	"aws_location_map",
	"aws_location_place_index",
	"aws_location_route_calculator",
	"aws_location_tracker",
	"aws_location_tracker_association",
}
