// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var LogsDefinitions = [...]string{
	"aws_cloudwatch_log_account_policy",
	"aws_cloudwatch_log_anomaly_detector",
	"aws_cloudwatch_log_data_protection_policy",
	"aws_cloudwatch_log_delivery",
	"aws_cloudwatch_log_delivery_destination",
	"aws_cloudwatch_log_delivery_destination_policy",
	"aws_cloudwatch_log_delivery_source",
	"aws_cloudwatch_log_destination",
	"aws_cloudwatch_log_destination_policy",
	"aws_cloudwatch_log_group",
	"aws_cloudwatch_log_index_policy",
	"aws_cloudwatch_log_metric_filter",
	"aws_cloudwatch_log_resource_policy",
	"aws_cloudwatch_log_s3_table_integration_source",
	"aws_cloudwatch_log_storage_tier_policy",
	"aws_cloudwatch_log_stream",
	"aws_cloudwatch_log_subscription_filter",
	"aws_cloudwatch_log_transformer",
	"aws_cloudwatch_query_definition",
}
