// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Macie2Definitions = [...]string{
	"aws_macie2_account",
	"aws_macie2_classification_export_configuration",
	"aws_macie2_classification_job",
	"aws_macie2_custom_data_identifier",
	"aws_macie2_findings_filter",
	"aws_macie2_invitation_accepter",
	"aws_macie2_member",
	"aws_macie2_organization_admin_account",
	"aws_macie2_organization_configuration",
}
