// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var MailmanagerDefinitions = [...]string{
	"aws_mailmanager_archive",
	"aws_mailmanager_ingress_point",
	"aws_mailmanager_relay",
	"aws_mailmanager_rule_set",
	"aws_mailmanager_traffic_policy",
}
