// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var MedialiveDefinitions = [...]string{
	"aws_medialive_channel",
	"aws_medialive_input",
	"aws_medialive_input_security_group",
	"aws_medialive_multiplex",
	"aws_medialive_multiplex_program",
}
