// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var MediastoreDefinitions = [...]string{
	"aws_media_store_container",
	"aws_media_store_container_policy",
}
