// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NeptuneDefinitions = [...]string{
	"aws_neptune_cluster",
	"aws_neptune_cluster_endpoint",
	"aws_neptune_cluster_instance",
	"aws_neptune_cluster_parameter_group",
	"aws_neptune_cluster_snapshot",
	"aws_neptune_event_subscription",
	"aws_neptune_global_cluster",
	"aws_neptune_parameter_group",
	"aws_neptune_subnet_group",
}
