// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NeptunegraphDefinitions = [...]string{
	"aws_neptunegraph_graph",
	"aws_neptunegraph_private_graph_endpoint",
}
