// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NetworkmanagerDefinitions = [...]string{
	"aws_networkmanager_attachment_accepter",
	"aws_networkmanager_attachment_routing_policy_label",
	"aws_networkmanager_connect_attachment",
	"aws_networkmanager_connect_peer",
	"aws_networkmanager_connection",
	"aws_networkmanager_core_network",
	"aws_networkmanager_core_network_policy_attachment",
	"aws_networkmanager_customer_gateway_association",
	"aws_networkmanager_device",
	"aws_networkmanager_dx_gateway_attachment",
	"aws_networkmanager_global_network",
	"aws_networkmanager_link",
	"aws_networkmanager_link_association",
	"aws_networkmanager_prefix_list_association",
	"aws_networkmanager_site",
	"aws_networkmanager_site_to_site_vpn_attachment",
	"aws_networkmanager_transit_gateway_connect_peer_association",
	"aws_networkmanager_transit_gateway_peering",
	"aws_networkmanager_transit_gateway_registration",
	"aws_networkmanager_transit_gateway_route_table_attachment",
	"aws_networkmanager_vpc_attachment",
}
