// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NetworkflowmonitorDefinitions = [...]string{
	"aws_networkflowmonitor_monitor",
	"aws_networkflowmonitor_scope",
}
