// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NetworkfirewallDefinitions = [...]string{
	"aws_networkfirewall_container_association",
	"aws_networkfirewall_firewall",
	"aws_networkfirewall_firewall_policy",
	"aws_networkfirewall_firewall_transit_gateway_attachment_accepter",
	"aws_networkfirewall_logging_configuration",
	"aws_networkfirewall_resource_policy",
	"aws_networkfirewall_rule_group",
	"aws_networkfirewall_tls_inspection_configuration",
	"aws_networkfirewall_vpc_endpoint_association",
}
