// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var NotificationsDefinitions = [...]string{
	"aws_notifications_channel_association",
	"aws_notifications_event_rule",
	"aws_notifications_managed_notification_account_contact_association",
	"aws_notifications_managed_notification_additional_channel_association",
	"aws_notifications_notification_configuration",
	"aws_notifications_notification_hub",
	"aws_notifications_organizational_unit_association",
	"aws_notifications_organizations_access",
}
