// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ObservabilityadminDefinitions = [...]string{
	"aws_observabilityadmin_centralization_rule_for_organization",
	"aws_observabilityadmin_s3_table_integration",
	"aws_observabilityadmin_telemetry_enrichment",
	"aws_observabilityadmin_telemetry_evaluation",
	"aws_observabilityadmin_telemetry_evaluation_for_organization",
	"aws_observabilityadmin_telemetry_pipeline",
	"aws_observabilityadmin_telemetry_rule",
	"aws_observabilityadmin_telemetry_rule_for_organization",
}
