// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var OdbDefinitions = [...]string{
	"aws_odb_cloud_autonomous_vm_cluster",
	"aws_odb_cloud_exadata_infrastructure",
	"aws_odb_cloud_vm_cluster",
	"aws_odb_iam_role_association",
	"aws_odb_network",
	"aws_odb_network_peering_connection",
}
