// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var OpensearchDefinitions = [...]string{
	"aws_opensearch_application",
	"aws_opensearch_authorize_vpc_endpoint_access",
	"aws_opensearch_domain",
	"aws_opensearch_domain_policy",
	"aws_opensearch_domain_saml_options",
	"aws_opensearch_inbound_connection_accepter",
	"aws_opensearch_outbound_connection",
	"aws_opensearch_package",
	"aws_opensearch_package_association",
	"aws_opensearch_vpc_endpoint",
}
