// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var OrganizationsDefinitions = [...]string{
	"aws_organizations_account",
	"aws_organizations_aws_service_access",
	"aws_organizations_delegated_administrator",
	"aws_organizations_organization",
	"aws_organizations_organizational_unit",
	"aws_organizations_policy",
	"aws_organizations_policy_attachment",
	"aws_organizations_resource_policy",
	"aws_organizations_tag",
}
