// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var OsisDefinitions = [...]string{
	"aws_osis_pipeline",
	"aws_osis_pipeline_endpoint",
	"aws_osis_resource_policy",
}
