// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var PaymentcryptographyDefinitions = [...]string{
	"aws_paymentcryptography_key",
	"aws_paymentcryptography_key_alias",
}
