// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var PinpointDefinitions = [...]string{
	"aws_pinpoint_adm_channel",
	"aws_pinpoint_apns_channel",
	"aws_pinpoint_apns_sandbox_channel",
	"aws_pinpoint_apns_voip_channel",
	"aws_pinpoint_apns_voip_sandbox_channel",
	"aws_pinpoint_app",
	"aws_pinpoint_baidu_channel",
	"aws_pinpoint_email_channel",
	"aws_pinpoint_email_template",
	"aws_pinpoint_event_stream",
	"aws_pinpoint_gcm_channel",
	"aws_pinpoint_sms_channel",
}
