// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var QuicksightDefinitions = [...]string{
	"aws_quicksight_account_settings",
	"aws_quicksight_account_subscription",
	"aws_quicksight_analysis",
	"aws_quicksight_custom_permissions",
	"aws_quicksight_dashboard",
	"aws_quicksight_data_set",
	"aws_quicksight_data_source",
	"aws_quicksight_folder",
	"aws_quicksight_folder_membership",
	"aws_quicksight_group",
	"aws_quicksight_group_membership",
	"aws_quicksight_iam_policy_assignment",
	"aws_quicksight_ingestion",
	"aws_quicksight_ip_restriction",
	"aws_quicksight_key_registration",
	"aws_quicksight_namespace",
	"aws_quicksight_refresh_schedule",
	"aws_quicksight_role_custom_permission",
	"aws_quicksight_role_membership",
	"aws_quicksight_template",
	"aws_quicksight_template_alias",
	"aws_quicksight_theme",
	"aws_quicksight_user",
	"aws_quicksight_user_custom_permission",
	"aws_quicksight_vpc_connection",
}
