// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var RamDefinitions = [...]string{
	"aws_ram_permission",
	"aws_ram_principal_association",
	"aws_ram_resource_association",
	"aws_ram_resource_share",
	"aws_ram_resource_share_accepter",
	"aws_ram_resource_share_associations_exclusive",
	"aws_ram_sharing_with_organization",
}
