// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var RedshiftserverlessDefinitions = [...]string{
	"aws_redshiftserverless_custom_domain_association",
	"aws_redshiftserverless_endpoint_access",
	"aws_redshiftserverless_namespace",
	"aws_redshiftserverless_resource_policy",
	"aws_redshiftserverless_snapshot",
	"aws_redshiftserverless_usage_limit",
	"aws_redshiftserverless_workgroup",
}
