// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var RedshiftDefinitions = [...]string{
	"aws_redshift_authentication_profile",
	"aws_redshift_cluster",
	"aws_redshift_cluster_iam_roles",
	"aws_redshift_cluster_snapshot",
	"aws_redshift_data_share_authorization",
	"aws_redshift_data_share_consumer_association",
	"aws_redshift_endpoint_access",
	"aws_redshift_endpoint_authorization",
	"aws_redshift_event_subscription",
	"aws_redshift_hsm_client_certificate",
	"aws_redshift_hsm_configuration",
	"aws_redshift_idc_application",
	"aws_redshift_integration",
	"aws_redshift_logging",
	"aws_redshift_namespace_registration",
	"aws_redshift_parameter_group",
	"aws_redshift_partner",
	"aws_redshift_resource_policy",
	"aws_redshift_scheduled_action",
	"aws_redshift_snapshot_copy",
	"aws_redshift_snapshot_copy_grant",
	"aws_redshift_snapshot_schedule",
	"aws_redshift_snapshot_schedule_association",
	"aws_redshift_subnet_group",
	"aws_redshift_usage_limit",
}
