// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var RekognitionDefinitions = [...]string{
	"aws_rekognition_collection",
	"aws_rekognition_project",
	"aws_rekognition_stream_processor",
}
