// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Resiliencehubv2Definitions = [...]string{
	"aws_resiliencehubv2_assertion",
	"aws_resiliencehubv2_input_source",
	"aws_resiliencehubv2_policy",
	"aws_resiliencehubv2_service",
	"aws_resiliencehubv2_service_function",
	"aws_resiliencehubv2_system",
	"aws_resiliencehubv2_user_journey",
}
