// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Resourceexplorer2Definitions = [...]string{
	"aws_resourceexplorer2_index",
	"aws_resourceexplorer2_view",
}
