// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var RolesanywhereDefinitions = [...]string{
	"aws_rolesanywhere_profile",
	"aws_rolesanywhere_trust_anchor",
}
