// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53recoveryreadinessDefinitions = [...]string{
	"aws_route53recoveryreadiness_cell",
	"aws_route53recoveryreadiness_readiness_check",
	"aws_route53recoveryreadiness_recovery_group",
	"aws_route53recoveryreadiness_resource_set",
}
