// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53resolverDefinitions = [...]string{
	"aws_route53_resolver_config",
	"aws_route53_resolver_dnssec_config",
	"aws_route53_resolver_endpoint",
	"aws_route53_resolver_firewall_config",
	"aws_route53_resolver_firewall_domain_list",
	"aws_route53_resolver_firewall_rule",
	"aws_route53_resolver_firewall_rule_group",
	"aws_route53_resolver_firewall_rule_group_association",
	"aws_route53_resolver_query_log_config",
	"aws_route53_resolver_query_log_config_association",
	"aws_route53_resolver_rule",
	"aws_route53_resolver_rule_association",
}
