// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53recoverycontrolconfigDefinitions = [...]string{
	"aws_route53recoverycontrolconfig_cluster",
	"aws_route53recoverycontrolconfig_control_panel",
	"aws_route53recoverycontrolconfig_routing_control",
	"aws_route53recoverycontrolconfig_safety_rule",
}
