// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53domainsDefinitions = [...]string{
	"aws_route53domains_delegation_signer_record",
	"aws_route53domains_domain",
	"aws_route53domains_registered_domain",
}
