// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53profilesDefinitions = [...]string{
	"aws_route53profiles_association",
	"aws_route53profiles_profile",
	"aws_route53profiles_resource_association",
}
