// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Route53Definitions = [...]string{
	"aws_route53_cidr_collection",
	"aws_route53_cidr_location",
	"aws_route53_delegation_set",
	"aws_route53_health_check",
	"aws_route53_hosted_zone_dnssec",
	"aws_route53_key_signing_key",
	"aws_route53_query_log",
	"aws_route53_record",
	"aws_route53_records_exclusive",
	"aws_route53_traffic_policy",
	"aws_route53_traffic_policy_instance",
	"aws_route53_vpc_association_authorization",
	"aws_route53_zone",
	"aws_route53_zone_association",
}
