// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var S3Definitions = [...]string{
	"aws_s3_bucket",
	"aws_s3_bucket_abac",
	"aws_s3_bucket_accelerate_configuration",
	"aws_s3_bucket_acl",
	"aws_s3_bucket_analytics_configuration",
	"aws_s3_bucket_cors_configuration",
	"aws_s3_bucket_intelligent_tiering_configuration",
	"aws_s3_bucket_inventory",
	"aws_s3_bucket_lifecycle_configuration",
	"aws_s3_bucket_logging",
	"aws_s3_bucket_metadata_configuration",
	"aws_s3_bucket_metric",
	"aws_s3_bucket_notification",
	"aws_s3_bucket_object",
	"aws_s3_bucket_object_lock_configuration",
	"aws_s3_bucket_ownership_controls",
	"aws_s3_bucket_policy",
	"aws_s3_bucket_public_access_block",
	"aws_s3_bucket_replication_configuration",
	"aws_s3_bucket_request_payment_configuration",
	"aws_s3_bucket_server_side_encryption_configuration",
	"aws_s3_bucket_versioning",
	"aws_s3_bucket_website_configuration",
	"aws_s3_directory_bucket",
	"aws_s3_object",
	"aws_s3_object_copy",
}
