// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var S3controlDefinitions = [...]string{
	"aws_s3_access_point",
	"aws_s3_account_public_access_block",
	"aws_s3control_access_grant",
	"aws_s3control_access_grants_instance",
	"aws_s3control_access_grants_instance_resource_policy",
	"aws_s3control_access_grants_location",
	"aws_s3control_access_point_policy",
	"aws_s3control_bucket",
	"aws_s3control_bucket_lifecycle_configuration",
	"aws_s3control_bucket_policy",
	"aws_s3control_directory_bucket_access_point_scope",
	"aws_s3control_multi_region_access_point",
	"aws_s3control_multi_region_access_point_policy",
	"aws_s3control_multi_region_access_point_routes",
	"aws_s3control_object_lambda_access_point",
	"aws_s3control_object_lambda_access_point_policy",
	"aws_s3control_storage_lens_configuration",
}
