// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var S3tablesDefinitions = [...]string{
	"aws_s3tables_namespace",
	"aws_s3tables_table",
	"aws_s3tables_table_bucket",
	"aws_s3tables_table_bucket_policy",
	"aws_s3tables_table_bucket_replication",
	"aws_s3tables_table_policy",
	"aws_s3tables_table_replication",
}
