// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var S3vectorsDefinitions = [...]string{
	"aws_s3vectors_index",
	"aws_s3vectors_vector_bucket",
	"aws_s3vectors_vector_bucket_policy",
}
