// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SchemasDefinitions = [...]string{
	"aws_schemas_discoverer",
	"aws_schemas_registry",
	"aws_schemas_registry_policy",
	"aws_schemas_schema",
}
