// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SecretsmanagerDefinitions = [...]string{
	"aws_secretsmanager_secret",
	"aws_secretsmanager_secret_policy",
	"aws_secretsmanager_secret_rotation",
	"aws_secretsmanager_secret_version",
	"aws_secretsmanager_tag",
}
