// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SecurityhubDefinitions = [...]string{
	"aws_securityhub_account",
	"aws_securityhub_account_v2",
	"aws_securityhub_action_target",
	"aws_securityhub_aggregator_v2",
	"aws_securityhub_automation_rule",
	"aws_securityhub_automation_rule_v2",
	"aws_securityhub_configuration_policy",
	"aws_securityhub_configuration_policy_association",
	"aws_securityhub_connector_v2",
	"aws_securityhub_feature_v2",
	"aws_securityhub_finding_aggregator",
	"aws_securityhub_insight",
	"aws_securityhub_invite_accepter",
	"aws_securityhub_member",
	"aws_securityhub_organization_admin_account",
	"aws_securityhub_organization_configuration",
	"aws_securityhub_product_subscription",
	"aws_securityhub_standards_control",
	"aws_securityhub_standards_control_association",
	"aws_securityhub_standards_subscription",
}
