// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SecuritylakeDefinitions = [...]string{
	"aws_securitylake_aws_log_source",
	"aws_securitylake_custom_log_source",
	"aws_securitylake_data_lake",
	"aws_securitylake_subscriber",
	"aws_securitylake_subscriber_notification",
}
