// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ServicediscoveryDefinitions = [...]string{
	"aws_service_discovery_http_namespace",
	"aws_service_discovery_instance",
	"aws_service_discovery_private_dns_namespace",
	"aws_service_discovery_public_dns_namespace",
	"aws_service_discovery_service",
}
