// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ServicequotasDefinitions = [...]string{
	"aws_servicequotas_auto_management",
	"aws_servicequotas_service_quota",
	"aws_servicequotas_template",
	"aws_servicequotas_template_association",
}
