// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ServicecatalogDefinitions = [...]string{
	"aws_servicecatalog_budget_resource_association",
	"aws_servicecatalog_constraint",
	"aws_servicecatalog_organizations_access",
	"aws_servicecatalog_portfolio",
	"aws_servicecatalog_portfolio_share",
	"aws_servicecatalog_principal_portfolio_association",
	"aws_servicecatalog_product",
	"aws_servicecatalog_product_portfolio_association",
	"aws_servicecatalog_provisioned_product",
	"aws_servicecatalog_provisioning_artifact",
	"aws_servicecatalog_service_action",
	"aws_servicecatalog_tag_option",
	"aws_servicecatalog_tag_option_resource_association",
}
