// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Sesv2Definitions = [...]string{
	"aws_sesv2_account_suppression_attributes",
	"aws_sesv2_account_vdm_attributes",
	"aws_sesv2_configuration_set",
	"aws_sesv2_configuration_set_event_destination",
	"aws_sesv2_contact_list",
	"aws_sesv2_dedicated_ip_assignment",
	"aws_sesv2_dedicated_ip_pool",
	"aws_sesv2_email_identity",
	"aws_sesv2_email_identity_feedback_attributes",
	"aws_sesv2_email_identity_mail_from_attributes",
	"aws_sesv2_email_identity_policy",
	"aws_sesv2_multi_region_endpoint",
	"aws_sesv2_tenant",
	"aws_sesv2_tenant_resource_association",
}
