// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var ShieldDefinitions = [...]string{
	"aws_shield_application_layer_automatic_response",
	"aws_shield_drt_access_log_bucket_association",
	"aws_shield_drt_access_role_arn_association",
	"aws_shield_proactive_engagement",
	"aws_shield_protection",
	"aws_shield_protection_group",
	"aws_shield_protection_health_check_association",
	"aws_shield_subscription",
}
