// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SignerDefinitions = [...]string{
	"aws_signer_signing_job",
	"aws_signer_signing_profile",
	"aws_signer_signing_profile_permission",
}
