// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SnsDefinitions = [...]string{
	"aws_sns_platform_application",
	"aws_sns_sms_preferences",
	"aws_sns_topic",
	"aws_sns_topic_data_protection_policy",
	"aws_sns_topic_policy",
	"aws_sns_topic_subscription",
}
