// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SqsDefinitions = [...]string{
	"aws_sqs_queue",
	"aws_sqs_queue_policy",
	"aws_sqs_queue_redrive_allow_policy",
	"aws_sqs_queue_redrive_policy",
}
