// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SsmcontactsDefinitions = [...]string{
	"aws_ssmcontacts_contact",
	"aws_ssmcontacts_contact_channel",
	"aws_ssmcontacts_plan",
	"aws_ssmcontacts_rotation",
}
