// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SsmincidentsDefinitions = [...]string{
	"aws_ssmincidents_replication_set",
	"aws_ssmincidents_response_plan",
}
