// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SsoadminDefinitions = [...]string{
	"aws_ssoadmin_account_assignment",
	"aws_ssoadmin_application",
	"aws_ssoadmin_application_access_scope",
	"aws_ssoadmin_application_assignment",
	"aws_ssoadmin_application_assignment_configuration",
	"aws_ssoadmin_customer_managed_policy_attachment",
	"aws_ssoadmin_customer_managed_policy_attachments_exclusive",
	"aws_ssoadmin_instance_access_control_attributes",
	"aws_ssoadmin_managed_policy_attachment",
	"aws_ssoadmin_managed_policy_attachments_exclusive",
	"aws_ssoadmin_permission_set",
	"aws_ssoadmin_permission_set_inline_policy",
	"aws_ssoadmin_permissions_boundary_attachment",
	"aws_ssoadmin_region",
	"aws_ssoadmin_trusted_token_issuer",
}
