// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var StoragegatewayDefinitions = [...]string{
	"aws_storagegateway_cache",
	"aws_storagegateway_cached_iscsi_volume",
	"aws_storagegateway_file_system_association",
	"aws_storagegateway_gateway",
	"aws_storagegateway_nfs_file_share",
	"aws_storagegateway_smb_file_share",
	"aws_storagegateway_stored_iscsi_volume",
	"aws_storagegateway_tape_pool",
	"aws_storagegateway_upload_buffer",
	"aws_storagegateway_working_storage",
}
