// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var SyntheticsDefinitions = [...]string{
	"aws_synthetics_canary",
	"aws_synthetics_group",
	"aws_synthetics_group_association",
}
