// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var TimestreamwriteDefinitions = [...]string{
	"aws_timestreamwrite_database",
	"aws_timestreamwrite_table",
}
