// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var TimestreaminfluxdbDefinitions = [...]string{
	"aws_timestreaminfluxdb_db_cluster",
	"aws_timestreaminfluxdb_db_instance",
}
