// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var TranscribeDefinitions = [...]string{
	"aws_transcribe_language_model",
	"aws_transcribe_medical_vocabulary",
	"aws_transcribe_vocabulary",
	"aws_transcribe_vocabulary_filter",
}
