// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var TransferDefinitions = [...]string{
	"aws_transfer_access",
	"aws_transfer_agreement",
	"aws_transfer_certificate",
	"aws_transfer_connector",
	"aws_transfer_host_key",
	"aws_transfer_profile",
	"aws_transfer_server",
	"aws_transfer_ssh_key",
	"aws_transfer_tag",
	"aws_transfer_user",
	"aws_transfer_web_app",
	"aws_transfer_web_app_customization",
	"aws_transfer_workflow",
}
