// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var VerifiedpermissionsDefinitions = [...]string{
	"aws_verifiedpermissions_identity_source",
	"aws_verifiedpermissions_policy",
	"aws_verifiedpermissions_policy_store",
	"aws_verifiedpermissions_policy_template",
	"aws_verifiedpermissions_schema",
}
