// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var VpclatticeDefinitions = [...]string{
	"aws_vpclattice_access_log_subscription",
	"aws_vpclattice_auth_policy",
	"aws_vpclattice_domain_verification",
	"aws_vpclattice_listener",
	"aws_vpclattice_listener_rule",
	"aws_vpclattice_resource_configuration",
	"aws_vpclattice_resource_gateway",
	"aws_vpclattice_resource_policy",
	"aws_vpclattice_service",
	"aws_vpclattice_service_network",
	"aws_vpclattice_service_network_resource_association",
	"aws_vpclattice_service_network_service_association",
	"aws_vpclattice_service_network_vpc_association",
	"aws_vpclattice_target_group",
	"aws_vpclattice_target_group_attachment",
}
