// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var WafregionalDefinitions = [...]string{
	"aws_wafregional_byte_match_set",
	"aws_wafregional_geo_match_set",
	"aws_wafregional_ipset",
	"aws_wafregional_rate_based_rule",
	"aws_wafregional_regex_match_set",
	"aws_wafregional_regex_pattern_set",
	"aws_wafregional_rule",
	"aws_wafregional_rule_group",
	"aws_wafregional_size_constraint_set",
	"aws_wafregional_sql_injection_match_set",
	"aws_wafregional_web_acl",
	"aws_wafregional_web_acl_association",
	"aws_wafregional_xss_match_set",
}
