// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var Wafv2Definitions = [...]string{
	"aws_wafv2_api_key",
	"aws_wafv2_ip_set",
	"aws_wafv2_regex_pattern_set",
	"aws_wafv2_rule_group",
	"aws_wafv2_web_acl",
	"aws_wafv2_web_acl_association",
	"aws_wafv2_web_acl_logging_configuration",
	"aws_wafv2_web_acl_rule",
	"aws_wafv2_web_acl_rule_group_association",
}
