// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var WorkspaceswebDefinitions = [...]string{
	"aws_workspacesweb_browser_settings",
	"aws_workspacesweb_browser_settings_association",
	"aws_workspacesweb_data_protection_settings",
	"aws_workspacesweb_data_protection_settings_association",
	"aws_workspacesweb_identity_provider",
	"aws_workspacesweb_ip_access_settings",
	"aws_workspacesweb_ip_access_settings_association",
	"aws_workspacesweb_network_settings",
	"aws_workspacesweb_network_settings_association",
	"aws_workspacesweb_portal",
	"aws_workspacesweb_session_logger",
	"aws_workspacesweb_session_logger_association",
	"aws_workspacesweb_trust_store",
	"aws_workspacesweb_trust_store_association",
	"aws_workspacesweb_user_access_logging_settings",
	"aws_workspacesweb_user_access_logging_settings_association",
	"aws_workspacesweb_user_settings",
	"aws_workspacesweb_user_settings_association",
}
