// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var WorkspacesDefinitions = [...]string{
	"aws_workspaces_connection_alias",
	"aws_workspaces_directory",
	"aws_workspaces_ip_group",
	"aws_workspaces_pool",
	"aws_workspaces_workspace",
}
