// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package resource

var XrayDefinitions = [...]string{
	"aws_xray_encryption_config",
	"aws_xray_group",
	"aws_xray_indexing_rule",
	"aws_xray_resource_policy",
	"aws_xray_sampling_rule",
	"aws_xray_trace_segment_destination",
}
