// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package ephemeralresource

var CognitoidentityDefinitions = [...]string{
	"aws_cognito_identity_openid_token_for_developer_identity",
}
