// Code generated by go run ./tools/awsdefinitions update; DO NOT EDIT.

package ephemeralresource

var SecretsmanagerDefinitions = [...]string{
	"aws_secretsmanager_random_password",
	"aws_secretsmanager_secret_version",
}
